cachix/devenv

src/modules/redis.nix, src/modules/top-level.nix
=> redis: Add redis option

src/devenv.nix
Fixes #27 
See https://unix.stackexchange.com/questions/38538/bash-dev-stderr-permission-denied
It seems to work fine now in Gitpod yeaa
=> fix: /dev/stderr requirement

src/modules/languages/erlang.nix
=> Init Erlang language

src/modules/languages/elixir.nix
=> Init language Elixir

src/modules/languages/dotnet.nix
Add support for .NET (dotnet) languages like C# and F#
=> Init dotnet

docs/getting-started.md, docs/overrides/home.html, docs/packages.md, src/devenv.nix, src/modules/top-level.nix
Fixes #4 
```
$ ./result/bin/devenv search ncdu
name         version  description
pkgs.ncdu    2.1.2    Disk usage analyzer with an ncurses interface
pkgs.ncdu_1  1.17     Disk usage analyzer with an ncurses interface
pkgs.ncdu_2  2.1.2    Disk usage analyzer with an ncurses interface
Found 3 results.
```
=> devenv search

src/devenv.nix
Simple if statement to default GC_ROOT to XDG_DATA_HOME if env variable is set. 
Fixes #29
=> default GC_ROOT to XDG_DATA_HOME

.envrc, docs/automatic-shell-activation.md, examples/simple/.envrc, examples/supported-languages/.envrc, src/devenv.nix
Also recommend starship.rs for PS1 integration.
=> Fix #10 direnv reloading and devnv up #13

devenv.lock, src/devenv.nix, src/flake.nix, src/modules/update-check.nix
=> update-check: avoid using env vars

.gitpod.yml, src/modules/mysql.nix, src/modules/top-level.nix
=> mysql: Add mysql option

src/modules/languages/php.nix
```
languages.php.enable = true;
languages.php.settings = ''
memory_limit=1G
'';
languages.php.extensions = [
languages.php.package.xdebug
];
```
=> Make PHP more configureable

src/modules/mongodb.nix, src/modules/top-level.nix
This is an attempt to add MongoDB as an option, based off of the previous mysql/postgres/redis options.
=> mongodb: Add MongoDB option

docs/reference/options.md, examples/process-compose/devenv.lock, examples/process-compose/devenv.nix, examples/process-compose/devenv.yaml, src/modules/postgres.nix, src/modules/processes.nix, src/modules/top-level.nix
=> feat(processes): add process-compose as new process.implementation option

src/modules/languages/terraform.nix
This PR adds support for [terraform](https://www.terraform.io/) and some base tools!
=> add terraform language support

src/devenv.nix
=> Add a comment into gitignore

examples/simple/devenv.nix
=> Default template should not create files

.gitpod.yml
I need to accept always the config when I spawn gitpod. Its annoying 😅
=> Accept nix flake config without user agreement in gitpod

src/modules/redis.nix
The working directory was not specified in redis. I wondered why I have in my project root a `dumb.rdb` file 😅
=> fix: redis working directory

.gitignore, .gitpod.yml, src/modules/elasticsearch.nix, src/modules/top-level.nix
Adds support for Elasticsearch and Opensearch.
Opensearch is not available yet in nixpkgs. I gave the PR already up https://github.com/NixOS/nixpkgs/pull/175000 . But I am using it locally 😅 
fixes #166
=> feat: add elasticsearch

examples/rust/devenv.lock, examples/rust/devenv.nix, examples/rust/devenv.yaml, src/modules/languages/rust.nix
Fixes https://github.com/cachix/devenv/issues/183
=> Rust: allow picking the version of the toolchain

src/modules/postgres.nix
make postgres more configureable to fix #180 
```nix
postgres.enable = true;
postgres.settings.timezone = "Europe/Berlin";
```
=> make postgres more configureable

src/modules/postgres.nix
=> postgres: add example for package. fixes #139

src/modules/memcached.nix, src/modules/top-level.nix
Someone asked in Discord how to get running memcached. added quickly a module
```
memcached.enable = true;
```
and it works
=> feat: add memcached support

flake.nix, src/modules/update-check.nix
=> check-update: disable when using flakes

src/modules/services/mailhog.nix
```
services.mailhog.enable = true;
```
Allows me to start an SMTP testing service :)
=> mailhog: init module

src/devenv.nix, src/flake.nix
Fixes #177 
PS: I made the capitals lowercase also for the options.
=> Support `devenv search` over options.

devenv.nix, src/modules/languages/python.nix, src/modules/top-level.nix
=> python: set PYTHONPATH

examples/ruby/Gemfile, examples/ruby/Gemfile.lock, examples/ruby/devenv.lock, src/modules/languages/ruby.nix
=> ruby: do not depend on host make, setup $RUBYLIB

.envrc, docs/community/contributing.md
=> docs: contributing guide

src/devenv.nix
=> cli: init create missing files

examples/simple/devenv.lock, src/devenv.nix
=> feat: auto run direnv allow

src/modules/top-level.nix
=> feat: symlink profile into local devenv folder

src/modules/top-level.nix
=> env: allow merging values

docs/reference/options.md, examples/supported-languages/devenv.nix, src/modules/languages/deno.nix
Added [deno](https://deno.land/) language from the nix [pkgs.deno](https://search.nixos.org/packages?channel=22.11&show=deno&from=0&size=50&sort=relevance&type=packages&query=deno)
=> Added deno language 

src/modules/top-level.nix
=> make sure .devenv folder exists

.github/workflows/buildtest.yml, .github/workflows/pull-requests.yml, .github/workflows/trusted.yml, devenv.lock, flake.lock
=> run builds on m1

flake.nix
It looks like this on my side:
=> flake.nix: add welcomeText about .gitignore

examples/scripts/devenv.lock, examples/scripts/devenv.yaml, src/modules/scripts.nix
=> Prioritize scripts

examples/rust/devenv.nix, src/modules/languages/rust.nix
=> rust: link frameworks on darwin

src/modules/services/mysql.nix
Extracted the password into own variable
=> mysql: fix password escaping, fixes #281

src/modules/services/postgres.nix
This change will allow users to specify SQL commands to run when the database is first initialized. An example use of this would to create database user(s). Though, you can run any arbitrary SQL.
resolves #313
=> User can specify SQL to run during initialization

src/modules/languages/ocaml.nix
=> Revert "Allow the user to use a different version of OCaml"

examples/mysql/devenv.lock, examples/mysql/devenv.nix, examples/mysql/devenv.yaml, src/modules/services/mysql.nix
correct ensured users and database creation that i might have broken before 🙈 
config used for validation:
```
services.mysql.enable = true;
services.mysql.package = pkgs.mariadb;
services.mysql.initialDatabases = lib.mkDefault [{ name = "test_database"; }];
services.mysql.ensureUsers = lib.mkDefault [
{
name = "test_user";
password = "test_password";
ensurePermissions = { "*.*" = "ALL PRIVILEGES"; };
}
];
services.mysql.settings = {
mysql = {
user = "test";
password = "test";
};
mysqldump = {
user = "test";
password = "test";
};
mysqladmin = {
user = "test";
password = "test";
};
};
```
=> correct mariadb database and user handling

src/modules/languages/php.nix
Allows disabling composer and adding own using packages
=> feat: make composer optional

src/modules/languages/swift.nix
Thanks to @stephank, we can support Swift as soon as it lands in nixpkgs-unstable!
I'm planning to test on https://github.com/PerfectlySoft/PerfectTemplate.git once Hydra catches up.
=> add Swift language support

docs/basics.md
=> fix basic example, fixes #363

src/modules/languages/php.nix
Currently services are little bit annoying with PHP like MySQL. We have to manually configure where the devenv socket is.
I have inlined it into the PHP config, so the dev don't have to think about it anymore
=> feat(php): make php easier with services

examples/caddy-php/devenv.nix, src/modules/services/blackfire.nix
=> php: cleanup with the new options

docs/guides/using-with-flakes.md
* Add a note explaining why `--impure` mode is necessary
* Make sure all sample commands use `--impure`
* Add a process example to let users know that `devenv up` works inside the flake shell.
* Improve wording throughout
Resolves #345.
Almost done, need to go over the last section as well.
=> Expand the flake guide

examples/simple-remote/.pre-commit-config.yaml
that file points into the nix store 😅
=> Delete unused file

examples/python-poetry/devenv.lock, src/modules/languages/python.nix
=> Fix poetry

src/modules/top-level.nix
Currently it is not possible to conveniently define erroneous state in modules. This happens when for instance options are incompatible with each-other and a clear error with instructions should be shown.
This adopts the `assertions` options that is used in NixOS modules as well.
I was thinking about how to properly test this, but the examples weren't fitting to test (on purpose) evaluation errors. I have manually done the following:
With `devenv.nix`:
```nix
{ pkgs, ... }:
{
assertions = [{ assertion = false; message = "Oh noes"; }];
}
```
It resulted in the following output:
```
error: Failed assertions:
- Oh noes
```
Note that it did _also_ output the whole stack trace, which isn't great for UX atm. That said, I thought it's better than not having error message.
The usecase for this …
=> add ability to define assertions

src/modules/languages/python.nix
=> Fix python install

src/modules/services/cassandra.nix
This is not yet fully working.
When using the default Cassandra package you will get warnings about python being an insecure package. There is also an issue where I seem unable to connect to the database using `cqlsh`.
When using the `cassandra_4` package, I am able to connect using the `cqlsh` tool.
I'm sure the code itself can be cleaned up as well.
=> Init Cassandra service

examples/supported-languages/devenv.nix, src/modules/languages/ansible.nix
This is a great project! This PR adds support for Ansible, it is heavily inspired by the existing Terraform module
=> feat: Add Ansible support

examples/mkcert/devenv.nix, examples/mkcert/devenv.yaml, src/modules/integrations/hostctl.nix, src/modules/integrations/mkcert.nix
Ive added mkcert as a basic integration and refaktored the hostctl integration, so both "feel" the same when using them. Feedback is appreciated :)
=> add mkcert as integration

src/modules/update-check.nix
Resolves https://github.com/cachix/devenv/issues/456
=> Fix echo output of update command when using an old devenv.lock

devcontainer/Dockerfile, devcontainer/nix-entrypoint.sh
=> fix devcontainer

src/modules/services/mysql.nix
=> fix: improve mysql escaping

src/modules/services/varnish.nix
Allows to use Varnish inside devenv
=> feat(module): add varnish

docs/guides/using-with-flakes.md, templates/simple/flake.nix, templates/terraform/flake.nix
Don't encourage users to create new instances of nixpkgs
=> remove instances of nixpkgs

examples/supported-languages/devenv.nix, src/modules/languages/pascal.nix
Add support for Pascal/Object Pascal ([TIOBE Index #⁠11](https://www.tiobe.com/tiobe-index/delphi-object-pascal/))
=> Add Pascal/Object Pascal language support

docs/reference/yaml-options.md, src/devenv-yaml.nix, src/flake.nix
=> feat: add support for permittedInsecurePackages

.github/workflows/buildtest.yml, devenv.lock, devenv.nix, examples/python/.test.sh, examples/python/devenv.nix, src/modules/languages/python.nix
```nix
{
languages.python = {
enable = true;
version = "3.7.16";
venv.enable = true;
venv.requirements = ''
requests
'';
};
}
```
=> python.venv.requirements

examples/jsonnet/.test.sh, examples/jsonnet/devenv.nix, examples/jsonnet/devenv.yaml, examples/supported-languages/devenv.nix, src/modules/languages/jsonnet.nix
Add support for the [jsonnet](https://jsonnet.org/) language.
=> feat: add jsonnet language support

docs/services.md
As a nix noob, it took me a while to figure out what fields are available.
=> Point to all service definitions in the docs.

examples/rubyonrails/.test.sh, examples/rubyonrails/Gemfile, examples/rubyonrails/README.md, examples/rubyonrails/devenv.nix, examples/rubyonrails/devenv.yaml
=> Add RubyOnRails example

docs/guides/using-with-flake-parts.md, templates/flake-parts/flake.nix
plus a round of proofreading in the second commit
=> doc, examples: flake-parts imports

examples/mysql/.test.sh, examples/mysql/devenv.nix, src/modules/services/mysql.nix
=> mysql: add test, fix db existance check

docs/reference/options.md, examples/javascript/.gitignore, examples/javascript/.test.sh, examples/javascript/devenv.nix, examples/javascript/devenv.yaml, examples/javascript/package-lock.json, examples/javascript/package.json, src/modules/languages/javascript.nix
npmInstall option runs `npm install` on package.json change.
=> javascript: add npmInstall option

src/devenv/cli.py
=> devenv print-dev-env --json

docs/guides/using-with-flake-parts.md, docs/inputs.md, templates/simple/flake.nix, templates/terraform/flake.nix
Updates nixos to the latest release and use helper for systems definition
=> docs: Update nixos release and systems helper

examples/varnish/.test.sh, examples/varnish/devenv.lock, examples/varnish/devenv.nix, examples/varnish/devenv.yaml, src/modules/services/varnish.nix
I need while developing Varnish xkey module. This is in the module collection which is already packaged, but it was not possible to configure it right now
=> varnish: allow using module collection

docs/integrations/github-actions.md
Notably, this mentions how to run multi-line run commands inside a devenv shell, which addresses a question I saw on our Discord.
=> Expand GitHub Actions docs into a full guide

docs/reference/yaml-options.md
Explicit instructions for what to do if you have an out of date dependency.
These would be clear for people new to Nix through devenv.
=> Update yaml-options.md with clear instructions for adding packages that aren't part of Nix packages

docs/scripts.md, examples/scripts/devenv.nix, src/modules/scripts.nix
Just some metadata that can be useful in various contexts like enterShell for example.
Closes: #887
=> Add description to script

docs/blog/posts/devenv-v0.6-generating-containers-and-instant-shell-activation.md
I was going through some docs and noticed that there was a typo in one of the instances of my username. Just a quick fix for it.
=> Fix my name in docs

src/devenv/cli.py
Add a --keep-going flag and handle ctrl-C during test running more gracefully.
=> "devenv test" improvements

docs/reference/yaml-options.md, src/devenv/yaml.py, src/modules/flake.tmpl.nix
Moved from https://github.com/cachix/devenv/pull/954
=> Support allowBroken

src/modules/services/mysql.nix
Otherwise config files outside devenv can get in the way and block database setup.
=> services/mysql: properly use wrappers during setup

src/modules/services/postgres.nix
it's just example code, but it should be correct anyway. cheers
=> fix: replace "CREATE USER" with "CREATE ROLE"

examples/phoenix/.test.sh, examples/phoenix/README.md, examples/phoenix/devenv.nix
patterned using example/rubyonrails
=> docs(phoenix): add example for elixir phoenix

docs/blog/posts/devenv-v1.0-rewrite-in-rust.md
=> Make edit pass on 1.0 release post

docs/blog/posts/devenv-v1.0-rewrite-in-rust.md
=> Make more release-post tweaks

docs/blog/posts/devenv-v1.0-rewrite-in-rust.md
Caught me while I was sleeping 😩.
=> Touch up 1.0 release post

docs/getting-started.md
Noticed this typo while reading the docs
=> Minor typo/grammar fix

devenv/init/.envrc, examples/simple/.envrc, examples/supported-languages/.envrc
Sorry. I checked in a wrong SHA256 hash. This one should be correct.
Run `direnv fetchurl https://raw.githubusercontent.com/cachix/devenv/95f329d49a8a5289d31e0982652f7058a189bfca/direnvrc` to check the hash.
=> Fixed hash in .envrc

src/modules/integrations/dotenv.nix
=> Support dotenv comments

docs/integrations/github-actions.md
devenv 1.0 complains: error: unexpected argument '-e' found
=> Fix multiline shell example in docs

devenv/src/main.rs, docs/containers.md
* Update documentation of `devenv container` command
* Update documentation
=> containers: documentation update

examples/terraform/.test.sh, examples/terraform/devenv.nix, examples/terraform/devenv.yaml
=> fix: Terraform example

docs/services.md
Simple update to reference `DEVENV_STATE` rather than `DEVENV_DOTFILE`
=> docs: $DEVENV_DOTFILE -> $DEVENV_STATE

src/modules/process-managers/process-compose.nix, src/modules/processes.nix
=> process-compose: use unix-socket

src/modules/languages/rust.nix
Previously, if `channel` was set to anything but `nixpkgs`, the rust toolchain would get added to the shell regardless of the value of `languages.rust.enable`.
Also deduped the logic that figures out which fenix channel to use.
=> rust: ensure rust can be disabled when using non-default channel

docs/scripts.md
Found bash best practice here: https://stackoverflow.com/a/4824637
=> Add alias/args example to scripts.md

examples/httpbin/.test.sh, examples/httpbin/devenv.nix, src/modules/services/httpbin.nix
Creates a new module for [httpbin](https://github.com/psf/httpbin).
=> httpbin: new module

devenv/src/main.rs
Fixes #11 
```shell-session
$ devenv repl
> devenv
{ 
...
}
=> add devenv repl

devenv/src/main.rs
=> fix: execution of devenv version in read only directory

src/modules/integrations/android.nix
Continuing the improvements for android flutter support like #1294
So far this is not something typically mentioned in the docs, so I did not adjust them either.
=> feat: make flutter package configurable

examples/android/devenv.nix, src/modules/integrations/android.nix
=> feat: Make android-studio optional

src/modules/languages/go.nix
=> Use the exact same Go package for delve and other go tools

src/modules/languages/deno.nix
This allows me to use e.g. deno from nixpkgs-unstable
=> deno: add package option

docs/guides/using-with-flake-parts.md
Correcting what was likely a cut/paste error.
=> 📝 update documentation.

src/modules/integrations/starship.nix
fixes https://github.com/cachix/devenv/issues/860
=> starship: don't mangle non-bash prompts for direnv users

src/modules/containers.nix
Fixed bug described in https://github.com/cachix/devenv/issues/1416
=> fix: hidden files and folders not included

.github/workflows/generate.yml, docs/reference/options.md, src/modules/containers.nix
=> docs: fix container option descriptions

docs/reference/yaml-options.md
IIUC, this is a default value that has not been updated.
=> Document default value

docs/reference/options.md, docs/supported-languages/r.md, examples/r/devenv.nix, src/modules/languages/r.nix
Option to install [radian](https://github.com/randy3k/radian) console added.
=> R: add radian console

src/modules/services/postgres.nix
=> postgres: create role without requiring a schema

docs/reference/options.md, docs/supported-languages/haskell.md, src/modules/languages/haskell.nix
=> docs: fix haskell defaults

docs/blog/posts/devenv-is-switchting-nix-implementation-to-tvix.md
Fix grammar: Add missing "to" in devenv-is-switchting-nix-implementation-to-tvix.md
=> Add missing "to" in devenv-is-switchting-nix-implementation-to-tvix.md

devenv/src/cli.rs, devenv/src/main.rs
=> add --version flag

examples/nginx/devenv.nix
This pull request includes a configuration for the Nginx service.
=> Add Nginx example

devenv/src/devenv.rs
=> devenv: fix compilation error

devenv-eval-cache/src/internal_log.rs
- Builds up activity messages from the log fields. This includes useful network info and fixes an issue where we'd print out empty log lines.
- Adjusts the log level for activity messages. These also have broken log levels when streamed from the daemon.
=> devenv: fix empty log lines being printed

docs/integrations/android.md
=> Ensures docs are in line with API for Android integration

docs/reference/options.md, docs/supported-languages/elixir.md, src/modules/languages/elixir.nix
=> elixir: sync the package for all git hooks that use elixir

src/modules/integrations/android.nix
=> flutter: bump JDK version to 17

devenv/src/devenv.rs
Disables the generate command.
Fixes #1733.
=> devenv: disable the generate command

src/modules/services/meilisearch.nix, tests/meilisearch/devenv.nix
This pull request is related to https://github.com/cachix/devenv/issues/1667
=> Fix/meilisearch 'error: invalid value '1' for '--no-analytics'

.github/workflows/buildtest.yml, .github/workflows/pin.yml
Let's see if this speeds things up a bit or not.
=> ci: use self-hosted x86_64-darwin runners

devenv/src/flake.tmpl.nix
=> devenv --system x86_64-linux build

devenv-eval-cache/src/command.rs
Turns out I already added support for empty content hashes at the library level.
=> eval-cache: fix bug where a removed input would force a cache miss

.devcontainer.json, docs/reference/options.md, src/modules/integrations/devcontainer.nix
Updates the name of the container: https://github.com/cachix/devenv/pkgs/container/devenv%2Fdevcontainer
=> devcontainer: update image url

flake-module.nix, flake.nix
Local overlays work fine in standalone devenv, not with flake-parts. I just added some code to make it work properly.
=> Fix: local overlays in flake module

devenv-tasks/src/lib.rs, devenv-tasks/src/main.rs, devenv/src/devenv.rs
Fixes #1647 
Fixes #1513 
cc @mcdonc
=> tasks: respect --quiet and produce less output in CI

devenv.lock, flake.lock
- Allow loading cli-options.nix through the git sandbox
=> nix: bump nix

devenv-tasks/src/lib.rs, devenv/src/devenv.rs
Fixes https://github.com/cachix/devenv/issues/1857
=> tasks: short-circuit ui logic in quiet mode

.github/workflows/buildtest.yml, docs/guides/using-with-flake-parts.md, docs/guides/using-with-flakes.md, mkdocs.yml
Hopefully this will give people a better sense of what they gain and (more likely) lose with flakes.
I especially hope this will discourage complete beginners to Nix from following this guide. It's much easier to start out with the devenv CLI and switch to flakes once there's a real need for it.
=> docs: break down pros and cons of devenv vs flakes

docs/supported-services/postgres.md, src/modules/services/postgres.nix, tests/postgresql-customperdbinit/.test.sh, tests/postgresql-customperdbinit/devenv.nix
This PR fixes #1673. If you agree with the approach to resolve this issue, please let me know so I can update the documentation as well.
=> Add services.postgres.initialDatabases.initialSQL config option

devenv-tasks/src/lib.rs, devenv-tasks/src/main.rs, devenv-tasks/src/ui.rs, devenv/src/devenv.rs
Fixes https://github.com/cachix/devenv/issues/1873
I need to review the changes and tests, not ready for merge.
=> Tasks: print stdout/stderr in verbose mode

src/modules/integrations/android.nix
matching https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/android.section.md#notes-on-environment-variables-in-android-projects-notes-on-environment-variables-in-android-projects
=> fix: android: Correct NDK path

docs/reference/yaml-options.md
Fix the documentation that was introduced with my previous PR: #1892
=> Fix devenv.yaml documentation

devenv/src/devenv.rs
`nix develop` always loads the user's bashrc, even when `clean` is enabled. This was feature was not transferred over in https://github.com/cachix/devenv/pull/1789.
We should probably diverge from `nix develop` and not load this if `clean` is enabled, but that is something that needs investigating.
We unfortunately can't handle this in the module system. `.bashrc` (or any rcfile) should be loaded early in the process, so that any env vars it sets don't override the dev shell (e.g. `$PATH`). `enterShell` is much too late for that. In the future, one we can evaluate derivations, we could create a modified `mkShell` and migrate this this setup into the module system.
=> devenv: load the user's bashrc

devenv/src/flake.tmpl.nix, tests/direnv/.test.sh
Fixed tests:
- direnv
- outputs
=> tests: fix failing tests

.github/workflows/test.yml, devenv/src/devenv.rs
As [reported on Discord](https://discord.com/channels/1036369714731036712/1036369758024650792/1390342801631481866).
=> tasks: source env for when we're running outside of devenv shell

devenv/src/devenv.rs, devenv/src/main.rs
=> devenv: fix issues running containers with `devenv container run`

src/modules/languages/python.nix
Fixes issues mentioned in #1959.
=> fix: revert wrong `UV_PYTHON` env. variable

devenv/src/nix.rs
Sets up a netrc file for Nix to use for auth against binary caches when `CACHIX_AUTH_TOKEN` is provided and `cachix.pull` is non-empty.
The downside here is that `--netrc-file` is not additive. Nix won't concatenate the configured netrc files, so any credentials already configured, e.g. in `~/.config/nix/netrc`, won't be used.
Fixes #2068 (TDB).
=> devenv: configure Nix to use the Cachix auth token

docs/overrides/home.html, docs/reference/options.md, docs/scripts.md, src/modules/scripts.nix
```nix
{ pkgs, ... }: {
scripts.build = {
exec = "yarn build";
packages = [ pkgs.yarn ];
};
}
```
=> scripts: support runtime packages

docs/reference/options.md, src/modules/top-level.nix
=> name: propagate into shell

devenv/init/devenv.nix
Fixes #2132.
Better ideas welcome!
```
> devenv up
Running tasks     devenv:processes:dev
Running           devenv:processes:dev
[devenv:processes:dev] [Running: ls -la]
[devenv:processes:dev] total 28
[devenv:processes:dev] drwxr-xr-x 10 sander _lpoperator  320 Sep  9 19:03 .
[devenv:processes:dev] drwxr-xr-x 46 sander _lpoperator 1472 Sep  9 19:02 ..
[devenv:processes:dev] drwxr-xr-x 19 sander _lpoperator  608 Sep  9 19:04 .devenv
[devenv:processes:dev] -rw-r--r--  1 sander _lpoperator 7778 Sep  9 19:02 .devenv.flake.nix
[devenv:processes:dev] drwxr-xr-x  2 sander _lpoperator   64 Sep  9 19:02 .direnv
[devenv:processes:dev] -rw-r--r--  1 sander _lpoperator  220 Sep  9 19:02 .envrc
[devenv:processes:dev] -rw-r--r--  1 sander _lpoperator   91 Sep  9 19:02 .gitignore
[devenv:processes:dev] …
```
=> devenv: update initial devenv.nix

src/modules/flake-compat.nix
=> flake-compat: wire up and expose tasks in the devenv flake wrapper

docs/automatic-shell-activation.md
Fix needed URLs
Add URL example
=> direnvrc has moved in repo
