- src/devenv.nix
- src/flake.nix
This allows overriding devenv.nix with changes that are local.
Think secrets, flipping flags, etc.
Fixes #37
> Import devenv.local.nix if it exists.

- src/devenv.nix
I started using devenv and intuitively used `devenv init myproject`, thinking it would create a new directory. It creates the files in my current directory.
This PR should add such support:
```console
$ devenv init myproject
$ cd myproject
```
I have not done full argument parsing/validation, as I wasn't sure you wanted to bother with that yet.
> init: support target directory argument

- src/modules/languages/java.nix
Currently it is not possible to change the JDK package for Java.
When doing so it helps to run Maven and Gradle in the same JDK as defined. This is because Maven plugins may be run that sometimes need to run in the same JDK as your application. This is why it is needed to also allow redefining the Maven/Gradle packages. By default, the package is overridden to use the same JDK as the application.
Enable options were added for maven and gradle to avoid unnecessary rebuilding of these packages.
`JAVA_HOME` environment variable is defined. This helps IDEs and tools to pick the right JDK.
Lastly I took the liberty to remove the `enterShell`. It didn't seem useful to see the maven version specifically each time the shell is entered. The JDK version would be more useful.
If this is acceptable …
> java: add package options

- flake.nix
This allows to simple get devshell via `nix shell github:cachix/devenv` without having to build nix.
> add devenv.cachix.org to nixConfig of flake.nix

- src/modules/postgres.nix
- $PGDATA is already an absolute path, no need to prefix with `pwd`
> fix: postgres not starting, because of wrong socket dir

- src/modules/languages/javascript.nix
This adds the ability to use a different node package with the javascript language enabled. I have used the same implementation as is used for Ruby.
I am not sure if this is the direction you are looking to go in to add support for different versions of packages but thought it was worth raising a PR and starting a conversation.
> Javascript: use different node package 

- docs/assets/extra.css
Adds some padding under `Get Started` button to balance the whitespace.
Before & After:
> fix(docs): add some whitespace under hero CTA button

- docs/reference/options.md
- examples/supported-languages/devenv.nix
- src/modules/languages/robotframework.nix
Well... robotframework is based on Python, so it come with Python interpreter and could conflict with ``languages.python.enable = true`` if it has different interpreter.
For a second, I thought if robotframework should be a Python application instead of package, but it is usual for custom Robot Framework Python libraries to import some API modules from robot modules.
Of course, this gets useful in the real world only with additional packages, and Nixpkgs seems to already have a few (including geckodriver and chromedriver to be used with seleniumlibrary):
https://search.nixos.org/packages?channel=22.05type=packages&query=robotframework
> language: robotframework

- src/devenv.nix
- src/flake.nix
- src/modules/info.nix
- src/modules/top-level.nix
```shell-session
$ devenv info
Inputs:
├───devenv: path:./src/modules
├───nix: github:domenkozar/nix/05c8b261e0b7848cc02c736d59316d7e02be8514
│   ├───lowdown-src: github:kristapsdz/lowdown/d2c2b44ff6c27b936ec27358a2653caaef8f73b8
│   ├───nixpkgs: github:NixOS/nixpkgs/365e1b3a859281cf11b94f87231adeabbdd878a2
│   └───nixpkgs-regression: github:NixOS/nixpkgs/215d4d0fd80ca5163643b03a33fde804a29cc1e2
├───nixpkgs: github:NixOS/nixpkgs/c6e5939c8fa2ab2230baf1378a34746e8db1aed7
└───pre-commit-hooks: github:cachix/pre-commit-hooks.nix/46fb5634676994bd333a94c8bd322eb1854ff223
├───flake-utils: github:numtide/flake-utils/6ee9ebb6b1ee695d2cacc4faa053a7b9baa76817
└───nixpkgs follows input 'nixpkgs'
- DEVENV_DOTFILE: /home/domen/dev/cachix/devenv/.devenv
- DEVENV_ROOT: /home/domen/dev/cachix/devenv
- …
```
> add devenv info command

- src/modules/languages/elm.nix
elm-format is widely used so I think it does not need to be configurable whether you want it or not.
I see scala includes scalafmt directly, so this follows the same pattern.
Unfortunately `elm-format --version` is not a valid option for this cli.
I'm not sure if it would be good to have a pre-commit hook to run the formatter, but this should be configurable since it's more opinionated which folders should be formatted, and at that point maybe I'm not sure what's a sensible default for devenv.
> Add elm-format when using elm

- examples/hivemind/devenv.lock
- examples/hivemind/devenv.nix
- examples/hivemind/devenv.yaml
- src/modules/processes.nix
This PR adds [hivemind](https://github.com/DarthSim/hivemind) as a new option to run processes defined in a Procfile.
`hivemind` is the "little brother" of `overmind` and works without running processes in a tmux session.
I have tested this PR by creating a new example in the `examples` directory and running `devenv up` there, which correctly starts two processes with hivemind.
> Add hivemind as a new Procfile interpreter

- src/modules/languages/v.nix
This PR adds support for [v](https://vlang.io/)!
Also, I wasn't sure if we'd be okay with the filename `v.nix` or if we wanted to go with `vlang.nix` to match the nixpkgs naming.
> add v language support

- src/modules/languages/ruby.nix
Set path by default to `env.BUNDLE_PATH = config.env.DEVENV_STATE + "/.bundle";`
It could be changed in the `devenv.nix` file. Example:
```
{ pkgs, config, nixpkgs-ruby, ... }:
{
env.BUNDLE_PATH = config.env.DEVENV_STATE + "/.bundle";
packages = [ pkgs.imagemagick pkgs.pkg-config ];
languages.ruby.enable = true;
languages.ruby.package = nixpkgs-ruby.lib.mkRuby { inherit pkgs; rubyVersion = "2.6.6"; };
}
```
> Set default path for ruby bundler

- examples/caddy-php/devenv.lock
- examples/caddy-php/devenv.nix
- examples/caddy-php/devenv.yaml
- src/modules/languages/php.nix
Allows to start a PHP-FPM server (fastcgi for PHP). 
Combined with Caddy, we have a full-featured PHP webserver environment
Added new example to show how it is working in examples/caddy-php
```nix
{ pkgs, config, ... }:
let
phpPackage = pkgs.php.buildEnv {
extraConfig = ''
memory_limit = 256M
'';
};
in
{
languages.php.enable = true;
languages.php.package = phpPackage;
languages.php.fpm.pools.web = {
settings = {
"pm" = "dynamic";
"pm.max_children" = 5;
"pm.start_servers" = 2;
"pm.min_spare_servers" = 1;
"pm.max_spare_servers" = 5;
};
};
caddy.enable = true;
caddy.virtualHosts."http://localhost:8000/" = {
extraConfig = ''
root * public
php_fastcgi unix/${config.languages.php.fpm.pools.web.socket}
file_server
'';
};
}
```
> feat: add phpfpm options

- src/modules/postgres.nix
Config was updated only once
Added two new options
```nix
postgres.listen_addresses = "127.0.0.1";
postgres.port = 5000;
```
By default, postgres still listens socket only with default port. With that options you can enable tcp again.
Also configured the default env vars for postgres to `psql` by default works https://www.postgresql.org/docs/current/libpq-envars.html
> improve postgres

- src/modules/mysql.nix
When the user have an `/etc/my.cnf` the mysql command will read it and pass default parameters like username and password
This will break the mysql server. So I added the forgotten parameter like on all other commands to here
> fix: mysql init with userland my.cnf

- src/modules/postgres.nix
the cat fails on first start as the folder is missing. I reordered the commands. Sorry 🙈 
```
After update: 16:09:09 postgres.1 | /nix/store/37c74ks31daya5p7xzjc3vdl1cf4n7j6-setup-postgres/bin/setup-postgres: line 6: .../.devenv/state/postgres/postgresql.conf: No such file or directory.
```
> fix: postgres startup if folder is missing

- docs/reference/options.md
- src/modules/blackfire.nix
- src/modules/top-level.nix
Allows to use https://blackfire.io together with PHP. Didn't tested Go / Python profiling.
Example Bllackfire together with PHP:
```diff
{ pkgs, config, ... }:
let
phpPackage = pkgs.php.buildEnv {
+   extensions = { all, enabled }: with all; enabled ++ [ (blackfire// { extensionName = "blackfire"; }) ];
extraConfig = ''
memory_limit = 256M
+     blackfire.agent_socket = "${config.blackfire.socket}";
'';
};
in
{
+ blackfire.enable = true;
+ blackfire.server-id = "xxxxxxxx";
+ blackfire.server-token = "xxxxxxxx";
+ blackfire.client-id = "xxxxxxxx";
+ blackfire.client-token = "xxxxxxxx";
languages.php.enable = true;
languages.php.package = phpPackage;
languages.php.fpm.pools.web = {
settings = {
"pm" = "dynamic";
"pm.max_children" = 5;
"pm.start_servers" = 2;
"pm.min_spare_servers" = 1; …
```
> feat: add blackfire support

- flake.nix
Currently, devenv creates a lot of extra entries in my flake.lock file, which increases download size and evaluation time.
By setting all dependencies to the same value, we can reduce this overhead.
> Avoid duplicate instances of dependencies by using follows.

- src/devenv.nix
readlink on macos does not have the same arguments as on linux. More
explicitly, it does not have `-f` as used in the devenv script.
> darwin: use nix readlink explicitly

- devenv.nix
- docs/guides/using-with-flakes-devshell.md
- flake.nix
- mkdocs.yml
- templates/simple/.envrc
- templates/simple/flake.nix
Currently it isn't trivial to start using devenv inside of a Nix flake. This PR attempts to ease the use.
First it introduces a `mkShell` lib function. This makes it possible to use devenv using:
```nix
devShells.x86_64-linux.default = devenv.lib.mkShell {
inherit inputs pkgs;
modules = [
{
}
];
};
```
In addition, I thought some documentation was useful. However I didn't want to confuse people with Nix flake things and conflate it with devenv. As a first step I added a Nix template that allows starting a Nix flake + direnv + devenv project using:
```
nix flake init --template cachix/devenv#simple
```
Are these things that you'd accept in devenv?
What would be a good place to document this?
> flake: make it easier to use devenv in Nix flake

- src/modules/adminer.nix
- src/modules/mysql.nix
- src/modules/top-level.nix
Adds adminer module
With adminer is like phpmyadmin phppgadmin but in a smaller file.
Can be enabled with
```
adminer.enable = true;
```
It disallows by default accessing users without password. https://www.adminer.org/en/password/
So I added a new option ensureUsers to create additional MySQL users
```
mysql.enable = true;
mysql.ensureUsers = [
{
name = "devenv";
password = "devenv";
ensurePermissions = {
"devenv.*" = "ALL PRIVILEGES";
};
}
];
```
**password** is optional and can be omited
> Add adminer

- src/modules/update-check.nix
> update-checker: warn correctly if devenv input is older than the cli

- src/modules/languages/c.nix
- src/modules/languages/clojure.nix
- src/modules/languages/cplusplus.nix
- src/modules/languages/cue.nix
- src/modules/languages/dotnet.nix
- src/modules/languages/elixir.nix
- src/modules/languages/elm.nix
- src/modules/languages/erlang.nix
- src/modules/languages/go.nix
- src/modules/languages/haskell.nix
- src/modules/languages/javascript.nix
- src/modules/languages/kotlin.nix
- src/modules/languages/lua.nix
- src/modules/languages/nim.nix
- src/modules/languages/nix.nix
- src/modules/languages/ocaml.nix
- src/modules/languages/perl.nix
- src/modules/languages/php.nix
- src/modules/languages/purescript.nix
- src/modules/languages/python.nix
- src/modules/languages/r.nix
- src/modules/languages/robotframework.nix
- src/modules/languages/ruby.nix
- src/modules/languages/rust.nix
- src/modules/languages/scala.nix
- src/modules/languages/terraform.nix
- src/modules/languages/typescript.nix
- src/modules/languages/v.nix
Resolves https://github.com/cachix/devenv/issues/199
This removes all `{tool} --version` in `enterShell`. `devenv info` is a better alternative at the moment.
> remove version output on enterShell

- examples/wiremock/devenv.lock
- examples/wiremock/devenv.nix
- examples/wiremock/devenv.yaml
- src/modules/services/wiremock.nix
In https://github.com/NixOS/nixpkgs/pull/203800, wiremock was added to nixpkgs. This is a HTTP(S) mock server to create a HTTP API endpoints. Useful for projects that need one or more other HTTP services to operate.
~The wiremock package is not yet on nixos-unstable, so I'll leave this PR in draft for now.~
The package is in nixpkgs-unstable and nixos-unstable now.
> add wiremock module

- examples/rust/devenv.nix
- src/modules/languages/rust.nix
Required for the rust-analyzer to work.
It's a bit of a questionable approach, but I feel like hacking around fenix's env generation would be even more tricky. At least it's explicit this way.
> Add the correct RUST_SRC_PATH

- examples/starship/devenv.lock
- examples/starship/devenv.nix
- examples/starship/devenv.yaml
- examples/starship/starship.toml
- src/modules/integrations/starship.nix
This PR adds a module to integrate the cross-shell prompt `Starship`.
The example inside the `examples` folder provides basic documentation about the options available in this module. The comments can easily be copied into a .md file to add it to the documentation website once the integration is reviewed and merged.
> add starship integration

- src/modules/services/mysql.nix
`sleep infinity` does not work on macOS. So I adjusted the path to use always `coreutils`. fixes #223
> mysql: fix missing coreutils

- src/modules/languages/rust.nix
The rust language support in devenv has two "backends" (nixpkgs and fenix). It's surprising to me that setting the `languages.rust.version` changes the backend. I think ideally this should be more obvious to the user, or there should just be a single backend for simplicity's sake. I have to wonder whether maintaining both is worth the effort.
Regardless, I ported the missing functionality into the nixpkgs backend, so now rust-analyzer and pre-commit hooks work there as well. I also added `rustfmt`, `clippy` and `rust-analyzer` to `PATH` so they can be picked up by editors (i.e. vscode). All packages are now overridable (e.g. i can use the nightly rustfmt with the stable rust toolchain).
You can override a package like so:
```nix
{ languages.rust.packages.rustfmt = …
```
> rust: feature parity with fenix

- src/modules/top-level.nix
This makes it easier to visually parse the end of the previous command's output.
> Color `(devenv)` in PS1 blue

- docs/getting-started.md
First time users skip it because "optional" and asking me then why it takes years to install Devenv
> Use word recommended for cachix

- examples/ruby/devenv.nix
- src/modules/languages/c.nix
- src/modules/languages/ruby.nix
- src/modules/top-level.nix
fixes #239 properly, based on feedback from #241
`nix-tree $DEVENV_PROFILE`
Before:
After:
> ruby: add on-by-default compiler tooling for native extensions, fix packages output unrolling

- src/modules/languages/rust.nix
> rust: fix iconv missing darwin

- src/modules/mkNakedShell.nix
Darwin always sets a `TMPDIR`. As the mkNakedShell removes the shell the `TMPDIR` gets `null` and breaks a lot of applications like VSCode with Direnv.
Before:
After:
> add workaround for tmpdir errors on Darwin, fixes #255

- docs/getting-started.md
Add `default` parameter to systemPackages import statement
> Fix instruction for declarative installation w/o flakes

- src/modules/services/mysql.nix
Enables users to set default user and passwords for mysql binaries that are automatically used.
```
services.mysql.settings = {
mysql = {
user = "test";
password = "test";
};
mysqldump = {
user = "test";
password = "test";
};
};
```
Without the changes the configure scripts breaks and the service cant be startet.
> Enable default users for mysql commands via mysqlOptions

- src/modules/languages/r.nix
Hello,
I added a config option to specify the R package. It is similar at how it is done for python.
I did that to be able to add additional dependencies to my R installation using  `rWrapper` such as:
```nix
languages.r = {
enable = true;
package = (pkgs.rWrapper.override{packages = with pkgs.rPackages; [ viridis tidyverse ];});
};
```
> languages/r: add option for R package

- flake.nix
- src/devenv-devShell.nix
- src/modules/processes.nix
- src/modules/update-check.nix
Remove the `DEVENV_PROFILE` entry from the processes `envList` set to avoid infinite recursions.
This happens when a devenv module uses the `config` parameter inside a scripts entry _and_ there are custom `processes` definitions. This is very common on projects that use devenv via the [nix flakes porcelain](https://github.com/cachix/devenv/blob/main/docs/guides/using-with-flakes.md).
```nix
{ config, ... }: {
processes.boom.exec = "echo boom";
scripts.devenv-up.exec = ''
${config.procfileScript}
'';
}
```
> fix: avoid infinite recursion

- src/modules/services/caddy.nix
The `services.caddy.dataDir` option was not being applied causing caddy to pollute state in the default locations - `~/.local/share/caddy` and `~/.config/caddy`
> caddy: fix unused dataDir option

- src/devenv-devShell.nix
- src/devenv.nix
- src/modules/integrations/hostctl.nix
- src/modules/processes.nix
- src/modules/top-level.nix
Fixes #227
Config looks like
```
hosts = [
"127.0.0.1 foo.de"
"127.0.0.1 bla.de"
];
```
It will be setup by entering the shell. I did add a proper "caching" so it's calling only hostctl when required because we need to run `sudo`.
To deactivate, the user has to run `deactivate-hosts` in the shell and leave the shell. Next opening of the shell readds them
> hostctl: init module

- src/modules/services/minio.nix
```nix
services.minio.enable = true;
services.minio.buckets = [ "some-test" ];
```
Allows me to create buckets on start.
> services/minio: add buckets option

- examples/python-venv/.gitignore
- examples/python-venv/README.md
- examples/python-venv/devenv.lock
- examples/python-venv/devenv.nix
- examples/python-venv/devenv.yaml
- src/modules/languages/python.nix
Currently Python always needs manually creating and activating a virtual environment. This can be done using `virtualenv`, but also `python -m venv venv`. It would be nice if this was done upon entering the devenv shell.
I previously also had poetry on top of this, but I thought it was better to split it up. First venv, maybe later poetry.
This also adds an example named `python-venv` to show how it would work.
> languages/python: add virtual environment option

- src/modules/processes.nix
Otherwise
```nix
{
env = {
ENVVAR = "Hello world";
};
processes.example.exec = "echo $ENVVAR";
}
```
results into
```
14:56:13 system    | example.1 started (pid=1518566)
14:56:13 example.1 | Helloworld
14:56:13 system    | example.1 stopped (rc=0)
```
> processes: quote env vars

- src/modules/languages/ocaml.nix
This will allow the user to specify which version of OCaml and associated tools that they would like to use for their project.
This will also include a few extra common tools within the OCaml ecosystem.
> Allow the user to use a different version of OCaml

- src/modules/languages/crystal.nix
This attempts to re-add crystal support. Based on #53, the compiler was missing.
Since crystal compiler support is based on nixpkgs currently building the package on some distros might fail. 
- When building on x86_64-darwin crystal 1.0 is attempted which lead to the following [make: *** [Makefile:93: compiler_spec] Illegal instruction: 4](https://gist.github.com/bcardiff/4531e4f9606692e9f531007880251cce). 
- On aarch64-darwin crystal 1.2.2 seems to be working, as long as `NIXPKGS_ALLOW_BROKEN=1` is set.
- On aarch64-linux crystal 1.2.2 seems to be working.
The latest release of crystal in nixpkg is 1.2.2, yet in https://github.com/crystal-lang/crystal is 1.6.2 .
I hope this will help to push the support of crystal in nixpkg.
If the state of the art of crystal in nixpkg is not good …
> Add Crystal Language

- src/modules/services/mysql.nix
When you mount tmpfs to `.devenv/state/mysql` folder the MySQL server won't start because the DB will be only created if the entire folder is missing.
> fix: mysql starting with empty folder

- devenv.lock
- examples/racket/devenv.lock
- examples/racket/devenv.nix
- examples/racket/devenv.yaml
- src/modules/languages/racket.nix
Add support for [Racket, the programming language](https://racket-lang.org/).
I suggest using the package `racket-minimal` by default. I've added an example using the Racket Full distribution to enable shell completion for `raco`.
P.S. Thanks for adding support for Julia upon my request on Mastodon 🎉
I saw how easy it was to contribute a new language so I decided to do the same.
Thanks for working on this!
Nix ❤️ devenv
> Add support for Racket

- src/modules/mkNakedShell.nix
- src/modules/top-level.nix
I use nix-darwin + home-manager, and the home-manager zsh + direnv modules to configure my shell. I had to make these changes to get the devenv environment to load using direnv. I believe that's down to me having `strict_env` enabled globally in my home-manager config:
```nix
programs.direnv = {
enable = true;
config.global.strict_env = true;
};
```
Per direnv docs, this may become the default in the future: https://direnv.net/man/direnv.toml.1.html#codestrictenvcode
> Fix direnv with strict_env enabled

- src/devenv.nix
Currently executing devenv in many cases looks like this:
```
$ devenv shell
Building shell ...
warning: Git tree '/home/bob.vanderlinden/projects/devenv' is dirty
evaluating derivation 'git+file:///home/bob.vanderlinden/projects/devenv#devShells.x86_64-linux.default'computing lock!computing lock!computing lock!computing lock!computing lock!computing lock!computing lock!com
Entering shell ...
```
I heard a collegue being a bit confused about the warning for a dirty git repo. I wanted to avoid this. After this change it looks like:
```
$ result/bin/devenv shell
Building shell ...
evaluating derivation 'git+file:///home/bob.vanderlinden/projects/devenv#devShells.x86_64-linux.default'computing lock!computing lock!computing lock!computing lock!computing lock!computing lock!computing lock!com …
```
> cli: suppress dirty git repository warnings

- .github/workflows/buildtest.yml
- examples/simple/devenv.lock
- src/modules/mkNakedShell.nix
Conveniently, `direnv exec ./examples/simple true` already fails, because the lockfile points to an older devenv that doesn't have #338. So I was able to build a failing test first, then fix it.
Though, whether my workflow concoction works, we'll just have to see. 🤷‍♂️
> Test direnv, and bash strict mode

- src/modules/update-check.nix
Missing quotes breaks the complete shell script
> Fix shell evaluation when devenv installed is newer

- src/modules/integrations/starship.nix
The comment was being appended to the config export causing an error. I've reorganized a bit to make the script a bit clearer.
Resolves #354.
> starship: fix setting a custom config

- src/flake.nix
Yep. This again. 😂  Resolves #314.
Might be faster to do this in jq, after filtering the JSON. But that requires a @domenkozar level of jq hackery.
The docbook warning is annoying, but I guess we just have to wait for nixpkgs to migrate to markdown 🤷 Once that's done, we could consider pretty-printing the markdown.
```
❯ devenv search starship
trace: warning: literalDocBook is deprecated, use literalMD instead
name           version  description
----           -------  -----------
pkgs.starship  1.12.0   A minimal, blazing fast, and extremely customizable prompt for any shell
jq: error (at <stdin>:76): object ({"_type":"l...) is not valid in a csv row
option  type  default  description
------  ----  -------  -----------
Found 1 packages and 4 options for 'starship'.
```
```
❯ …
```
> search: unpack Nix types when generating the options

- src/modules/languages/raku.nix
Adds simple language support for the [Raku Programming Language](https://www.raku.org/) by providing the [Rakudo Compiler - Rakudo Compiler for Raku Programming Language](https://rakudo.org/) implementation of Raku.
> Language Support: Raku

- src/modules/languages/gawk.nix
WIP PR (still requires testing) to add GNU Awk language support including shared library extension provided by `gawkextlib`.
> language support: GNU Awk

- docs/getting-started.md
Currently people starting with devenv are instructed to use an URL to a specific version of devenv (like `v0.5.1`). This makes upgrading using `nix-env` and `nix profile` a bit strange.
The UX looks as follows:
```console
$ nix profile install github:cachix/devenv/v0.5.1
...
$ nix profile list
0 github:cachix/devenv/latest#defaultPackage.x86_64-linux ...
$ nix profile remove 0
$ nix profile install github:cachix/devenv/v0.5.2
```
This can be improved a bit by using the stable branch:
```console
$ nix profile install github:cachix/devenv/latest
...
$ nix profile list
0 github:cachix/devenv/latest#defaultPackage.x86_64-linux ...
$ nix profile upgrade 0
```
This also aligns with what Nix suggests in `nix profile` configuration to upgrade all packages:
```console
$ nix profile install …
```
> docs/getting-started: use latest branch instead of tag

- src/modules/languages/php.nix
Depends on #301 
Allows to use phps by fossar directly
```
languages.php.enable = true;
languages.php.version = "8.1";
languages.php.ini = ''
memory_limit = 2G
'';
languages.php.extensions = [ "redis" "amqp" ];
```
When you use a PHP version which is not in nixpkgs, you get:
```
error: To use languages.php.version, you need to add the following to your devenv.yaml:
inputs:
phps:
url: github:fossar/nix-phps
inputs:
nixpkgs:
follows: nixpkgs
```
after adding phps to inputs it's working then
> First class phps support

- examples/supported-languages/devenv.lock
This fixes
```
error: Package ‘swift-5.6.2’ in «github:NixOS/nixpkgs/ea692c2ad1afd6384e171eabef4f0887d2b882d3»/pkgs/development/compilers/swift/default.nix:466 is not supported on ‘x86_64-darwin’, refusing to evaluate.
a) To temporarily allow packages that are unsupported for this system, you can use an environment variable
for a single invocation of the nix tools.
$ export NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1
Note: For `nix shell`, `nix build`, `nix develop` or any other Nix 2.4+
(Flake) command, `--impure` must be passed in order to read this
environment variable.
b) For `nixos-rebuild` you can set
{ nixpkgs.config.allowUnsupportedSystem = true; }
in configuration.nix to override this.
c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
{ allowUnsupportedSystem …
```
> update lock file

- src/modules/top-level.nix
Set `LOCALE_ARCHIVE` if missing to avoid locale issues on non-NixOS  systems. Resolves #353.
@domenkozar, there's a second solution here, which is to use the archive that already ships with the OS: `/usr/lib/locale/locale-archive`.  I tested it out on Ubuntu, but I have no idea how trustworthy this location is. If we really wanted to, we could first check the local path and then set it to `glibcLocalesUtf8` as fallback. Thoughts?
| Before | After |
| -------| ------|
| <img width="1512" alt="Screenshot 2023-02-07 at 21 38 55" src="https://user-images.githubusercontent.com/7572407/217331569-c70da3f6-a777-4bf7-90a7-bd34fd63ad1d.png"> |  <img width="1512" alt="Screenshot 2023-02-07 at 22 14 20" src="https://user-images.githubusercontent.com/7572407/217331600-c2f46d42-ddb1-427f-a906-111fa5fc93 …
> Set LOCALE_ARCHIVE if missing on non-NixOS hosts

- src/modules/top-level.nix
I've noticed that since `v0.5` long command lines wrap around and start overwriting the previous line.
Wrapping the color codes in a `\[..\]` seem to do the trick. Not a bash expert, so there might be a better way of doing this :shrug: 
going off https://askubuntu.com/questions/24358/how-do-i-get-long-command-lines-to-wrap-to-the-next-line
> properly escape color codes to avoid long command lines wraping back on themselves

- src/devenv.nix
Currently whenever a user doesn't have the `column` command, `devenv search` will fail.
For instance, I tried using devenv in `docker run -it ubuntu`. It resulted in the following output:
```
$ devenv search firefox
...
/home/me/.nix-profile/bin/devenv: line 100: column: command not found
```
This change should resolve that issue.
> cli: use column from util-linux package

- examples/texlive/devenv.nix
- examples/texlive/devenv.yaml
- src/modules/languages/texlive.nix
This contains a new module for Tex Live under `languages.texlive`.
The module itself is taken almost verbatim from Home-Manager, hence the comment and license header.
> add TeX Live support

- src/modules/languages/raku.nix
The description string set in `lib.mkEnableOption` breaks the documentation logic of https://devenv.sh/reference/options/#languagesrakuenable as it is displayed there as `Whether to enable Enable tools for Raku development..`, this PR fixes this.
> raku.nix: fixed lib.mkEnableOption string to not break web documentation

- src/modules/info.nix
- src/modules/processes.nix
- src/modules/scripts.nix
- src/modules/top-level.nix
This allows extending `devenv info` by adding:
```
{
sectionInfo."foo" = [ "myitem" ];
}
```
Still not sure about `sectionInfo` naming :)
> info: make sections pluggable

- src/modules/languages/go.nix
- Allow changing the GO version
- Fix go version conflict when you have go already installed, fixes #346 
- Isolate installed go packages inside devenv into into state/go, fixes #389 
- Isolated directory is also added to normal PATH
- Install all required go packages to use VSCode with language server (I guess other editors too)
```
languages.go = {
enable = true;
package = pkgs.go_1_20;
};
```
> Give go language more love

- src/modules/languages/crystal.nix
We removed from a while ago all version outputs in the terminal. Seems like forgotten here
> remove version output of crystal

- src/modules/languages/ruby.nix
- src/modules/top-level.nix
Currently whenever both `languages.ruby.version` and `languages.ruby.versionFile` are set, a confusing error message is shown:
```
error: The option `languages.ruby.package' is defined multiple times while it's expected to be unique.
Definition values:
- In `«github:cachix/devenv/3f845b2aff58d0ae27d9777500fe0c80b837ffb2»/src/modules/languages/ruby.nix': <derivation ruby-3.2.1>
- In `«github:cachix/devenv/3f845b2aff58d0ae27d9777500fe0c80b837ffb2»/src/modules/languages/ruby.nix': <derivation ruby-3.2.1>
Use `lib.mkForce value` or `lib.mkDefault value` to change the priority on any of these definitions.
```
After this PR it'll look like:
```
error: Failed assertions:
- `languages.ruby.version` and `languages.ruby.versionFile` are both set.
Only one of the two may be set. Remove one of the …
```
> ruby: assert version and versionFile not both set at once

- src/modules/languages/python.nix
Resolves #336
This PR includes 3 changes
22adea33daf57df14debc6cf6bc55b9db1ddfad5 is to resolve #336. It recreates venv each time devenv-profile is updated.
While working on this change I ran into syntax errors in my enterShell script. This resulted in errors like:
```
$ devenv shell
Building shell ...
Entering shell ...
bash: eval: line 231: syntax error near unexpected token `devenv'
bash: eval: line 231: `export PS1="\[\e[0;34m\](devenv)\[\e[0m\] ${PS1-}"'
```
It was hard to pin down where the problem actually lays, so I decided to move the venv and poetry scripts from enterShell to separate .sh files. This made the error messages clearer and the enterShell code more readable. See 057b1c019ae27a4cfd5eef37b88a7b20b8ba8bef
Lastly I noticed that there could be problems with running poetry …
> python: rebuild venv when devenv-profile is updated 

- src/modules/processes.nix
fixes breakage caused by https://github.com/cachix/devenv/commit/8bc83de411910ec5ed9759f8478c49639326e5f0
Bug caused `"/` folders to be created in `$DEVENV_ROOT`.
> fix(process-compose): do not escape strings for process-compose env vars

- src/modules/services/postgres.nix
When readiness probe fails for any reason, the whole process-compose process is terminated without these changes.
> feat(postgres + process-compose): faster shutdown + restart on failure

- src/modules/languages/go.nix
Installed Go Tools must have the same version as the installed toolchain. 
VSCode annoys always on any startup
> feat(go): use correct go version for tools

- docs/reference/yaml-options.md
- examples/overlays/devenv.nix
- examples/overlays/devenv.yaml
- src/devenv-yaml.nix
- src/devenv.nix
- src/flake.nix
Fixes #154 #185 
You can now do `devenv.yaml`:
```yaml
allowUnfree: true
inputs:
nixpkgs:
url: github:NixOS/nixpkgs/nixpkgs-unstable
rust-overlay:
url: github:oxalica/rust-overlay
overlays:
- default
```
> allowUnfree and overlays

- .envrc
- direnvrc
- docs/reference/options.md
- examples/simple/.envrc
- examples/supported-languages/.envrc
- src/devenv.nix
- src/modules/languages/raku.nix
- Fixes #382 #133 #237 
It differs to `nix-direnv` by being devenv specific:
- it tracks `imports` section of `devenv.yaml`
- it removes non-flake code
- it removes GC roots that are handled by devenv
Needs testing.
> Caching direnv integration

- docs/integrations/github-actions.md
Currently the documented version to install in GitHub Actions is 0.5, where-as 0.5.1 is the latest version. I was contemplating whether `latest` needed to be used, but I don't know whether that is a good idea already, since parts of devenv still rely on the cli itself.
> docs/github-actions: use devenv version 0.5.1

- .gitignore
- src/modules/services/postgres.nix
fixes https://github.com/cachix/devenv/issues/453
I tried to fix this properly by modifying the offending line:
https://github.com/cachix/devenv/blob/main/src/modules/processes.nix#L142
But regardless, the YAML file was written with the non-merged values (despite the NixOS module system stating that `config` should be always the final resolved value).
Given the severity of the bug, this is an intermediate quick fix. We should investigate where the override serialization problem exists.
> fix(postgres): remove override options, as currently they are serialized

- flake.nix
- mkdocs.yml
* Escape carets in the headers (see pre-commit or container options).
* Rewrite the declarations field to point to the GitHub repo where these options are defined.
Closes #359.
| Before | After |
| ------- | ---- |
| <img width="1512" alt="Screenshot 2023-03-02 at 21 23 57" src="https://user-images.githubusercontent.com/7572407/222505711-61733fb4-f20c-415d-95cf-1d9f01f09ba6.png"> | <img width="1512" alt="Screenshot 2023-03-02 at 21 24 09" src="https://user-images.githubusercontent.com/7572407/222505829-11d9f22e-90ca-4190-991e-56590ca48720.png"> |
> Update the reference docs for the the new doc renderer

- templates/simple/.envrc
Resolves #463
This changes .envrc so that it won't exit with code 1. This keeps envrc intact and will allow envrc to reload devenv.nix automatically when the file has changed.
In addition, this shows an additional stderr line to explain to the user that the devenv build has failed and the devenv environment is not available.
> envrc: give explanation on failing devenv builds

- src/devenv-devShell.nix
- src/devenv.nix
This removes the (inconsistent) colons at the end of commands in the help text, to make the help text a bit more readable.
Before:
```
[...]
Commands:
init:                     Scaffold devenv.yaml, devenv.nix, and .envrc inside the current directory.
init TARGET:              Scaffold devenv.yaml, devenv.nix, and .envrc inside TARGET directory.
search NAME:              Search packages matching NAME in nixpkgs input.
shell:                    Activate the developer environment.
shell CMD [args]:         Run CMD with ARGS in the developer environment. Useful when scripting.
container [options] NAME  Generate a container for NAME. See devenv container --help and http://devenv.sh/containers
info:                     Print information about the current developer environment.
[...]
```
After: …
> docs: strip colons from help text

- direnvrc
Resolved https://github.com/cachix/devenv/issues/463
Currently whenever print-dev-env fails, direnvrc exits with a failure.
This makes watch_file and other direnv changes be rolled back. It results in the devenv.nix file not being watched anymore.
I did the same for failure to parse `devenv.yaml`.
In addition, the error message now directs the user to devenv.nix.
Lastly I saw some places where `log_error` seemed like a nicer alternative to `log_status`.
> direnvrc: avoid errors where possible

- src/devenv.nix
Currently the util-linux package is used for the column cli. This is the only dependency for which util-linux is used. It results in quite a significant addition to the closure size.
util-linuxMinimal is somewhat smaller and also includes the column command.
I used `nix-tree` to check the closure size of the devenv command:
Before:
After:
It is still big, but at least it is smaller :sweat_smile:
Since python is already part of the closure, it might be a good idea to base everything on python and remove dependencies on util-linux-minimal, findutils, coreutils and jq.
This could help CI builds quite a bit in reducing the time it takes to fetch devenv.sh.
> use util-linuxMinimal instead of util-linux for column

- src/modules/services/mysql.nix
This fixes #469 
Any input on making it more maintainable or idiomatic is very welcome.
I'm quite new to writing prod software in nix :sweat_smile:
> fix: allow setting a non default timzone for mysql

- src/modules/languages/dotnet.nix
This PR introduces:
- `package` option
- [DOTNET_ROOT](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-environment-variables#dotnet_root-dotnet_rootx86) environment variable
- `icu` package on the `LD_LIBRARY_PATH` for [globalization](https://learn.microsoft.com/en-us/dotnet/core/extensions/globalization-icu)
> refactor(dotnet): add package option and needed environment variables

- docs/common-patterns.md
Especially the missing semicolon leads to an interminable error output.
> Fix two errors in Rosetta pattern

- devenv.nix
- docs/guides/using-with-flake-parts.md
- flake-module.nix
- flake.nix
- src/modules/update-check.nix
- templates/flake-parts/flake.nix
Makes devenv usable for flake-parts users.
> flake.nix: Add flakeModule

- flake.nix
flake-compat is exposing packages.default so this restores building
devenv with `nix-build`.
> flake: use packages.default instead of defaultPackage

- .envrc
This makes it easier to iterate on devenv and the direnvrc. Run `direnv
reload` and get the latest version.
> .envrc: use own devenv and direnvrc

- src/modules/services/elasticsearch.nix
- src/modules/services/opensearch.nix
Decouple OpenSearch from Elasticsearch Module like we did in nixpkgs.
- Removed OpenSearch support from Elasticsearch + added assert so the users migrate to the new option
- Used new style of options to the module to be more flexible than elasticsearch
```
services.opensearch = {
enable = true;
settings."node.name" = "foo";
};
```
> feat: add opensearch options

- .envrc
direnv hangs without that and I cannot accept it
> fix: hanging direnv

- src/modules/languages/python.nix
Currently devenv manages its own virtualenv in DEVENV_STATE/venv. In most circumstances this works fine. However, since poetry in some cases wants to manage its own virtualenv it breaks down.
To reproduce the bug:
* Initialize devenv with venv and poetry.
* Initialize pyproject.toml
* Change the python version in pyproject.toml to one that doesn't match the python version in devenv.
* Run poetry install _or_ rerun devenv
Poetry will (by default) create a new virtualenv in $HOME and use that, instead of the DEVENV_STATE/venv one from devenv.
[It is not possible to instruct poetry to specifically use the virtualenv that devenv created](https://github.com/python-poetry/poetry/issues/1579). However, it is possible to instruct poetry to use `PROJECT_ROOT/.venv` and it is able to create it when …
> python: rework how venv and poetry are handled

- src/modules/services/redis.nix
Based on postgres `readiness_probe` with same timeouts and periods.
> Added readiness_probe for Redis using redis-cli

- src/devenv.nix
I tried exporting a shell container to a file. I ran into `error: --registry must not have an argument`. Or just `error:` without a message if you use a space instead of an equals sign.
Same error when you try to run the example from the docs (`devenv container shell --registry docker://ghcr.io/ --copy`)
This commit fixes it.
> add missing argument to container registry option

- src/modules/services/redis.nix
This allows the user to use a non-default port
> Add -p option to redis rediness check

- src/devenv.nix
Currently devenv uses the date executable that is available in PATH. This means that under OSX a date executable is used that doesn't support `N` formatting, which leads to `gc` directories being stored in seconds instead of milliseconds.
This patch makes sure that date from coreutils is always used. This should fix problems with conflicting gc files when multiple devenv's are building in parallel.
I ran into this issue because collegues under MacOS were getting the following error:
Notice the `N` at the end :cry:
> use date from coreutils

- src/modules/languages/python.nix
Currently when poetry is enabled, a virtualenv is created by poetry and `poetry run` is able to operate correctly. However, it currently only works with `poetry run` while most users will expect to have the virtualenv already activated.
This patch adds automatic activation for poetry and enables it by default. This behavior is in line with poetry's behavior before https://github.com/cachix/devenv/pull/522 was introduced.
> python: automatic virtualenv activation for poetry

- devenv.nix
- examples/python-venv/.test.sh
- examples/ruby/.test.sh
Resolves https://github.com/cachix/devenv/issues/542
Currently during the tests the devenvs of the examples are build, but there isn't a check to see whether the options of the example are behaving as they were intended.
This changes allows examples to have a `.test.sh` file that is executed.
As an example (meta) I've added a test for python-venv to check whether the virtual environment has loaded correctly and a test for ruby to check whether Ruby can require gems in Gemfile.
> allow examples to have custom tests

- examples/python-poetry/.test.sh
As a follow-up from both https://github.com/cachix/devenv/pull/543 and https://github.com/cachix/devenv/pull/544, this adds a test for python-poetry that checks whether poetry packages can be imported.
> examples: python-poetry: add test

- src/modules/languages/python.nix
Currently `poetry` is called in one instance with just `poetry`. There were cases where the poetry binary from `devenv`'s root project leaked into the devenv of the python-poetry test. This often is not a problem, but in this case it was a poetry version that was built against a different glibc, resulting in an error.
I've tried to harden the poetry module a bit more by explicitly calling all executables to avoid leakage of executables from a parent environment.
While debugging also found a minor issue when manually executing poetry after removing `.venv`, poetry will create a new `.venv` directory. In this case devenv should remove it and create a new symlink. This is what `ln -sf` was meant to do, however it instead created a symlink inside the `.venv` directory. I tried to avoid this …
> python: avoid using existing virtual env or poetry binary

- src/modules/debug.nix
- src/modules/mkNakedShell.nix
- src/modules/top-level.nix
Currently when there are problems it is hard to reproduce and hard to find out which parts of `enterShell` are at fault. To get more information about what is going on I thought it was nice to have a debug option in devenv that enables debugging in bash when running the shellHook/enterShell scripts.
This was done in response to https://github.com/cachix/devenv/issues/555, which seemed like an issue that was hard to reproduce.
This allows people to add `devenv.debug = true;` to their configuration and it would show all lines that were executed by bash.
I thought about adding a test, but I couldn't find a good/nice way to do so. Suggestions are welcome!
> devenv: add devenv.debug option

- src/modules/languages/python.nix
Fixes #558.
This fixes an infinite recursion error that originated as a result of trying to set an environment variable using the output of another environment variable.
> python: evaluate $DEVENV_PROFILE at runtime instead of in nix

- devcontainer/nix.conf
Correctly run devenv.sh in a devcontainer.
Solution provided at https://github.com/NixOS/nix/issues/5258#issuecomment-921030592
Closes #560
I have now tested my changes and it works perfectly on my M1 Mac book.
My only concern is that the docker image is 1.47GB which is much bigger than the official image at 944MB. I am not sure what happened there since the only difference is a single line in the nix.conf.
> fix error when devenv ci in devcontainer

- docs/reference/yaml-options.md
The example specifies both a revision and a branch name. This gives the following nix error:
URL 'github:NixOS/nixpkgs/master?rev=a95ed9fe764c3ba2bf2d2fa223012c379cd6b32e' contains both a commit hash and a branch/tag name master a95ed9fe764c3ba2bf2d2fa223012c379cd6b32e
> Fixed wrong url example

- devenv.nix
- docs/guides/using-with-flake-parts.md
- docs/guides/using-with-flakes.md
- src/modules/mkNakedShell.nix
- src/modules/top-level.nix
Currently it is possible to run devenv without `--impure`. However, strange things may happen, because `$PWD` is not set. This results in `env.DEVENV_ROOT` being `""`, which results in various other variables to contain an invalid path (like `/.devenv`).
This will go unnoticed, but can cause problems.
This PR makes fetchign `env.DEVENV_ROOT` throw an error whenever it is fetched without Nix running in `--impure` mode.
I can imagine this can also cause annoyances for people who are using devenv without _actually_ depending on `DEVENV_ROOT`. So it isn't a clear win in that regard. I thought I'd just suggest the change.
This was in response to https://github.com/cachix/devenv/issues/550
> devenv: assert --impure is used

- flake.nix
- src/devenv.nix
As a follow-up from #545 I thought there might be more instances where executable were used from the global system. This turned out to be true.
I'm not sure whether any of the currently used executables result in incompatiblities, but I thought to avoid such potential problems in the future.
I also took the liberty to align the nix and devenv-yaml calls so they look the same as calls to other packages.
I checked for usage of other external commands by using `PATH=""` in the top of the devenv-script and look for command not found errors.
> devenv: use explicit package paths for executables

- src/modules/containers.nix
Currently when the image built by devenv is run with custom arguments, `Cmd` will be replaced. As a result, the script created by `mkEntrypoint` would not get executed. For example, the following command will fail because `bash` is not in the path:
``` bash
docker run -it my-image bash
```
even when bash is added to packages:
``` nix
packages = [pkg.bash];
```
This PR set `Entrypoint` to `cfg.entrypoint` so that is would not be overwritten by docker run arguments.
``` nix
Entrypoint = cfg.entrypoint;
```
Now docker run works:
``` bash
docker run -it my-image bash
```
> Put `cfg.entrypoint` to`Entrypoint` instead of `Cmd`

- examples/python-poetry/.test.sh
- examples/python-poetry/devenv.nix
- src/modules/languages/python.nix
Currently when using python, the `PYTHONPATH` always contains the literal string `$DEVENV_PROFILE`. This is incorrect, as the variable is not resolved.
In addition, it would be nice to add to any `PYTHONPATH` that is already there, just like we're doing with `PATH`.
I've added a test that fails in the current implementation and succeeds with the patch.
> python: fix PYTHONPATH using literal "$DEVENV_PROFILE"

- flake.lock
Makes the latest hooks added to `pre-commit-hooks` available in `devenv`
> Update pre-commit-hooks input

- src/modules/languages/deno.nix
With this change, Deno cache and installed packages will be installed in the devenv state folder and be project-specific instead of global.
> feat: lock deno to project scope

- src/modules/services/rabbitmq.nix
When booting, the processes expect that whatever host is in the "node name" is resolvable by DNS. Disabling reverse DNS lookups does not refute this requirement. This change provides an environment variable that RabbitMQ is expecting to find with a value that should be resolvable on all machines: `localhost`.
Resolves #356
> Always provide a node name to rabbitmq

- src/modules/containers.nix
fixes #591 
`nix flake check` when consuming devenv in a flake results in errors due to `containers.processes`, `containers.shell`, and `containers.""` not having the name attribute set. This PR addresses this by setting the `name` attribute appropriately, and not creating the container with the empty name.
> [containers] conditionally set isBuilding, add names to default containers

- docs/basics.md
This existing link points to a broken page: https://nix.dev/tutorials/nix-language
Updated it to point to the new page (AFAICT): https://nix.dev/tutorials/first-steps/nix-language
> Update nix lang link in basics doc

- devenv.nix
Tested on both NixOS and macOS.
macOS also requires #607 to work.
> docs: add missing build dependency

- examples/ruby/Gemfile.lock
- examples/ruby/devenv.nix
Add the missing native dependencies to the ruby example on macOS.
Resolves #564.
> ruby: fix macos tests

- examples/ruby/.test.sh
- examples/ruby/Gemfile
- examples/ruby/Gemfile.lock
- examples/ruby/devenv.yaml
- src/modules/languages/ruby.nix
Currently there is no way to disable bundler nor is it possible to alter the bundler package.
In addition, there was a problem with the prioritization of the ruby/bundler packages, as modern ruby packages include a bundler executable.
This was reported here: https://github.com/bobvanderlinden/nixpkgs-ruby/issues/72
I also wanted to avoid regressions, so I added a stricter example/test.
Resolves https://github.com/bobvanderlinden/nixpkgs-ruby/issues/72
> ruby: add bundler options

- src/modules/languages/ruby.nix
Currently only the examples/ruby/devenv.yaml mention the use of `follows: nixpkgs`. This was not the case yet for the assertion message if nixpkgs-ruby input doesn't exist.
> ruby: add "follows: nixpkgs" in assertion message

- examples/postgres/devenv.nix
- src/modules/services/postgres.nix
This is a convenience option to install a list of PostgreSQL extensions. The set of available extensions is provided as an argument.
```nix
{
services.postgres.enable = true;
services.postgres.extensions = extensions: [ extensions.postgis ];
}
```
You could already do this by modifying the package with `withPackages` and then overriding `services.postgres.package`. The new option has two advantages over the existing approach:
1. It's easier to find in the documentation.
2. Users unfamiliar with nixpkgs are unlikely to be aware of
`pkgs.postgresql.withPackages` specifically, or the pattern in
general.
The NixOS services calls this option `extraPlugins`. First of all, that's not what PostgreSQL calls them. Second, you have to manually source the extensions from `pkgs.postgresql.pkgs` and …
> postgres: add an `extensions` option

- examples/gleam/devenv.yaml
The nixpkgs repository already has a community maintained derivation for Gleam. Use that in the example Gleam project.
People would only need to use vic/gleam-nix flake when building non-released Gleam versions or contributing to Gleam itself.
Closes #610 by using already pre-cached nixpkgs gleam.
> Use nixpkgs#gleam package instead of vic/gleam-nix

- examples/meilisearch/devenv.nix
- examples/meilisearch/devenv.yaml
- src/modules/services/meilisearch.nix
An open-source, lightning-fast, and hyper-relevant search engine that fits effortlessly into your workflow.
> Add Meilisearch service

- src/modules/languages/javascript.nix
```nix
{
languages.javascript.enable = true;
languages.javascript.package = pkgs.nodejs-16_x;
packages = [ (pkgs.yarn.override { nodejs = pkgs.nodejs-16_x; }) ];
}
{
languages.javascript.enable = true;
languages.javascript.package = pkgs.nodejs-16_x;
scripts.yarn.exec = ''exec corepack yarn "$@"'';
}
{
languages.javascript.enable = true;
languages.javascript.package = pkgs.nodejs-16_x;
languages.javascript.corepack.enable = true;
}
```
> javascript: add corepack option

- src/modules/languages/python.nix
Resolves https://github.com/cachix/devenv/issues/621
This adds two options.
`groups = [ <group> ]` is the equivalent of using `poetry install --with <group>`.
It only supports adding groups, as I have not looked into supporting `--only` nor `--without`. Maybe someone else could give an opinion of this, as I have never used these cli options before :sweat_smile:.
`extras = [ <extra> ]` is the equivalent of using `poetry install --extras <extra>`.
I have now also made sure that the command line option of `poetry install` are included in the checksum that determines whether `poetry install` should be re-run. If any of the arguments changes, it will run poetry install the next time devenv shell initializes.
> python: poetry: add groups and extras options

- src/modules/languages/python.nix
In #631 poetry gained the ability to install extras and groups. I tested out the extras feature today and found a bug: If you specify multiple extras, then the following install command is generated:
`poetry install --extras extra1 extra2`
The problem is that poetry treats `extra2` as an argument to the install command. Thus, this PR adds quotation marks as follows:
`poetry install --extras "extra1 extra2"`
While I was at it, I also added another option to select `--all-extras`.
> Fix poetry extras

- src/modules/languages/haskell.nix
The `languageServer` option type inside the `haskell` language module is set to  `lib.types.nullOr lib.types.package`, however, the `packages` section does not check for `null` values causing the following error:
```
error: A definition for option `perSystem.aarch64-darwin.devenv.shells.default.packages."[definition 1-entry 2]"' is not of type `package'. Definition values:
- In `/nix/store/95czchz5fgjcak3y1y5cizx22irqa09w-source/src/modules/languages/haskell.nix': null
```
Relevant code snippet:
```nix
languages.haskell = {
enable = true;
languageServer = null;
};
```
> haskell: Fix error when `languageServer` is set to `null`

- src/modules/languages/haskell.nix
This change makes `stack` package parameterizable so it could be customized or skipped if is set to `null`
> haskell: Parameterize `stack` package

- examples/process-compose/devenv.nix
- src/modules/services/memcached.nix
This adds a simple bash-based readiness check. It will fail if the server is faulted for whatever reason. I chose `bash` over `nc` because it is fairly prevalent throughout all of `nixpkgs` and you are likely to have it already loaded in your store.
> Add readiness check for memcached

- src/modules/services/elasticsearch.nix
This adds a readiness check that is exactly like the healthcheck in the official Docker library.
> Add readiness check to elasticsearch

- src/modules/services/rabbitmq.nix
This adds a readiness check very similar to what is done in the Docker world to check for rabbitmq readiness.
I have some async workers that can boot faster than rabbitmq, so it would be nice to have a healthcheck that gates my code until the process actually responds.
> Add readiness check for rabbitmq

- src/modules/services/memcached.nix
This is an alternative healthcheck for memcached. The prior one worked when executed with `bash -c 'healthcheck'` but failed silently when I removed the `bash` wrapper. This changes the healthcheck to use `echo | nc`, and I have tested this locally by taking the generated `process-compose.yaml` and modifying the command in the YAML. I have also tested using both `127.0.0.1` and `::1` for the `listen` parameter. I was not as rigorous as I should have been after I modified the last `memcached` PR from feedback.
> Use nc for healthcheck

- src/modules/processes.nix
I'm using the `process-compose` implementation and I'd like to be able to [run specific processes](https://github.com/F1bonacc1/process-compose#-run-only-specific-processes) sometimes. 
For example, suppose I have a `server` process and a `postgres` process, there are times when I just want to start the `postgres` process for tests. Something like:
```console
devenv up postgres
```
Which is hopefully what this PR adds support for. 
I must admit I'm not that familiar with the other implementations (`honcho` et al.) but I'm assuming the same change applies for them?
> Pass arguments to `devenv up` through to implementation

- src/modules/process-managers/hivemind.nix
- src/modules/process-managers/honcho.nix
- src/modules/process-managers/overmind.nix
- src/modules/process-managers/process-compose.nix
- src/modules/processes.nix
- src/modules/top-level.nix
As [discussed on Discord](https://discord.com/channels/1036369714731036712/1036369758024650792/1119268576206016576) this is a proposal implementation for splitting up the process-managers into separate modules.
I must say that this became a bit bigger than I initially anticipated, but it seemed like the refactorings were still useful and backwards-compatible.
There are a few todo's in here to propose further changes, but first wanted to get feedback on this proposal as-is.
While working on this I also felt it might be a good idea to move generating the Procfile and env-file into a `pkgs.formats.procfile` and `pkgs.formats.envfile`. That way these implementations can be reused, but do not need to reside as options (process-compose doesn't use them for instance, as do a number of other …
> move process implementations to separate modules

- src/modules/services/postgres.nix
I have a project with ~150 migration files going back to 2016, added by many different people using different conventions. The commits in this PR are required in order for me to successfully apply all those sql files. 
The repo is private (sorry!), but I've tried to give a representative example of each fix in its commit message.
> Make postgres initialDatabases schema creation more robust

- examples/temporal/.test.sh
- examples/temporal/devenv.nix
- examples/temporal/devenv.yaml
- src/modules/services/temporal.nix
> temporal: add temporal service

- src/modules/services/opensearch.nix
Since `opensearch` is a fork of `elasticsearch`, I basically copy-and-pasted the previous readiness probe for `opensearch`. The root path on the configured port/address should return a `200 OK` when the server is up and running.
> opensearch readiness probe

- src/modules/services/opensearch.nix
This is hard to test locally, but the configuration for `opensearch` is different than `elasticsearch`. It uses `cfg.settings."network.host"` and `cfg.settings."http.port"` instead of `listenAddress` and `port`.
> Use cfg.settings instead for opensearch readiness check

- src/modules/languages/crystal.nix
Crystal needs at least a linker available and `pkg-config`, but other parts of the C toolchain are also often useful.
A more minimal implementation would be adding `pkgs.gcc` and `pkgs.pkg-config` as the bare minimum. The idea of enabling the entire C language is copied from the Rust configuration, so I figure it should be fine for Crystal as well.
> Enable `languages.c` for Crystal

- src/modules/services/postgres.nix
I ran into an issue where I couldn't create a db user named "default"
> [Bugfix]: Escape shell args so quotes don't get removed in intialScript

- flake.lock
The command used to update the `pre-commit-hooks` input:
```
nix flake lock --update-input pre-commit-hooks
```
> feat(flake.lock): Update pre-commit-hooks input

- src/modules/processes.nix
Small teak to allow multi-line bash strings for processes.exec
> [feature]: Add ability for process.exec to be multiline

- src/modules/process-managers/process-compose.nix
Included on the original process-compose PR:
https://github.com/cachix/devenv/blob/095be0c31e4d90d515acee30bb95818cf19900ef/src/modules/processes.nix#L125-L126
But removed in this PR:
https://github.com/cachix/devenv/pull/668
See previous version:
https://github.com/cachix/devenv/blob/eae002528893ba224f88b35163ff3ec273f67784/src/modules/processes.nix#L56-L60
> Honor process-compose `port` and `tui` options

- src/devenv-devShell.nix
- src/modules/containers.nix
- src/modules/languages/python.nix
- src/modules/languages/rust.nix
- src/modules/process-managers/process-compose.nix
- src/modules/processes.nix
- src/modules/top-level.nix
The best way to solve this for now is to set these as part of config.devenv.* namespace and reference these instead of from config.env when setting env.
Also, when using flakes integration let's evaluate the whole config when invoking `devenv up` instead of when building the devenv cli.
Fixes #580
> env: fix infinite recursion errors

- src/modules/languages/php.nix
Since #692 PHP does not stop anymore and hangs.
This is because the multilining added an additional shell wrapper around which does not exec. As wrapping is not nesscarry anymore, I removed it for PHP so it works like before
> fix: php-fpm termination

- src/modules/top-level.nix
This PR allows the user to set `devenv.root` to `.` as a workaround to #658
> Make devenv.root be overridable

- src/modules/services/mailpit.nix
[Mailpit](https://github.com/axllent/mailpit) is fancy replacement for Mailhog.
Has been added today to nixpkgs, so the pipeline can fail: https://github.com/NixOS/nixpkgs/pull/242829
> feat: add mailpit

- src/modules/services/blackfire.nix
By default is Blackfire Application performance monitoring enabled and this produces a lot of logs:
```
Error detected during APM traces upload: Cannot send an HTTP request to the Blackfire API.
```
So this disables this by default and adds an option to enable. It makes only sense to enable it for an live website 😅
> feat(blackfire): add option to enable apm

- src/modules/languages/php.nix
Tailscale + PHP imap is right now evil see https://github.com/php/php-src/issues/11673
Right now it's not possible to disable "builtin" extensions. So I added a additional option to do this
> feat(php): allow disabling pre-enabled php extensions

- src/modules/services/memcached.nix
This is an improvement that was [found in a previous PR](https://github.com/cachix/devenv/pull/653#issuecomment-1620532170). If you don't send a `quit` it seems that the healthcheck process will sometimes hang and not exit, which will lead `process-compose` to thinking the healthcheck times out and fails.
Thanks @volker-schukai for the suggestion!
> Send `quit` to memcached to terminate healthcheck successfully

- examples/mailpit/.test.sh
- examples/mailpit/devenv.nix
- examples/mailpit/devenv.yaml
- src/modules/services/mailpit.nix
cc @shyim 
I understand the argument handling was based on the mailhog module, and noticed it didn't uses `escapeShellArg(s)`. Not sure if that was intended?
> Mailpit: persist db, add sendmail binary, add example

- src/modules/languages/php.nix
- src/modules/processes.nix
This appears to fix #595. Overmind [creates a shell wrapper](https://github.com/DarthSim/overmind/blob/7d970570e9208812eaf3782d695bc13700bee48e/start/command.go#L166-L181), but that shell process sticks and interferes with sending signals to PHP-FPM. The `exec` here appears to otherwise work fine with other process managers (tested with caddy-php example on macos)
> processes: eliminate shell wrapper

- src/modules/languages/python.nix
We should switch to `.venv` since #735
> Set VENV_PATH properly

- src/modules/languages/shell.nix
Makes usage of bats nicer if the blessed libs are easily available. I didn't notice that these weren't automatically part of bats.
> lang/shell: Add bats libs to bats package

- flake-module.nix
- src/devenv-devShell.nix
This PR adds devenv-up as a package so that it can be created from `nix build`, which fixes #711
> fix(flake-module): add devenv-up as a package

- src/modules/integrations/mkcert.nix
Hi everyone. Just want to begin with a huge thanks for devenv. I'm a new user
to nix in general, and devenv has been a _really_ nice to work with.
I did run into an issue with the `mkcert` integration when using Firefox. I think
this PR should fix the problem:
* the `certutil` binary is in the `nssTools` package
* Also includes the `certutil` binary in `PATH` during `mkcert -install` since that 
appears to be when its actually required -- to trust the new certificate
authority. I kept it in both lines in case I'm wrong about that or in the future
`mkcert` changes that.
> Fix mkcert Integration When nss Is Used

- src/modules/services/postgres.nix
This makes the initialization process for `postgres` use the "multi-user" mode instead of "single-user" mode. This change allows for creating extensions automatically on first boot (like `timescaledb`).
[Initial log output](https://raw.githubusercontent.com/penguincoder/devenv-timescaledb-test/main/log-output.txt)
[Minimal reproduction git repo](https://github.com/penguincoder/devenv-timescaledb-test)
You should be able to clone the reproduction repo and then do a `devenv shell` then `devenv up` and it should have a bunch of TimescaleDB in the output. I haven't tested this much more extensively than that, but it does appear to be reliable.
The process more or less mimics the pattern from the Docker library, but it's not much more than using `pg_ctl` to start the server at the beginning of …
> [FEAT] Do not use single-user mode when initializing postgres

- examples/python-poetry/.test.sh
The `.test.sh` has been broken in `examples/python-poetry` since I think 0d08083c19d1f03302ca17eba920852c171e942c. This changes the test to look for a directory (not a link into `$DEVENV_STATE`) named `.venv` in `$DEVENV_ROOT`.
> [BUG] fix python-poetry .test.sh to work with new .venv directory

- src/modules/services/mysql.nix
Corrects the error: Plugin mysqlx reported: 'Setup of socket: '/run/mysqld/mysqlx.sock' failed, can't create lock file /run/mysqld/mysqlx.sock.lock'
With the fix the console only shows the success message: X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /path/to/devenv/project/.devenv/state/mysqlx.sock
Tested with mysql80 and mariadb default package
> feat: correct mysqlx socket location

- src/modules/languages/rust.nix
If custom toolchain is configured, use tools (cargo/rustftm/clippy)
from it, while still allowing a user to `lib.mkForce` them and specify
some custom ones.
> rust: use tools from custom toolchain for pre-commit hooks

- README.md
Would you like to add the "Built with Nix" badge?
I initially tried to add the badge for the Matrix channel, but the shields.io badge somehow shows it as being inaccessible with both the room name and the alias. This is probably due to the room not being world readable (chat history visible to anyone).
> Add "Built with Nix" badge

- docs/languages.md
On my first attempt to use devshell, the languages example broke for me. It seems like the way to specify versions might have changed?
> Update languages example to use rust channel.

- src/modules/services/couchdb.nix
Many of the settings were `camelCase`, but it looks like CouchDB expects `snake_case`, so all of it was being ignored.
It also looks like CouchDB expects the last config file specified to be writable. I made it look more like NixOS, which also passes `default.ini` as the first file.
> CouchDB service fixes

- src/modules/process-managers/process-compose.nix
- src/modules/processes.nix
I ran into an issue where process-compose failed to initialize minio properly (on macOS). I noticed we were putting the entire minio `startScript` in the process-compose config. Wrapping it in `writeShellScript` (like other process managers do) seems to fix it. I suspect process-compose was running the script using a different shell, perhaps the old bash 3.x on macOS.
This also updates the `devenv info` output, which was also dumping the startup script.
> Fix `devenv info` and process-compose config containing entire startup scripts

- src/modules/services/postgres.nix
The existing implementation creates a `pg-init-XXXXXX` directory inside of `$DEVENV_ROOT` and _also_ in `$DEVENV_STATE`. This change makes it so that the one in the root directory is no longer created.
> [BUG] Use a full path `mktemp` to not leave orphans in `$DEVENV_ROOT`

- examples/phoenix/.test.sh
- examples/phoenix/README.md
- examples/phoenix/devenv.nix
- examples/phoenix/devenv.yaml
This is my attempt for an elixir phoenix example.
Based on the ruby on rails example: https://github.com/cachix/devenv/commit/8d246b0c01721c546cdef6786560e5bd1ffae689 
Some differences I noted were:
- Rails uses unix domain socket by default [and also defaults to username: "$USER" and password: ""](https://stackoverflow.com/a/24039062), while phoenix has a default `username: "postgres" and password: "postgres"`.
So what I did was to make postgres listen to `127.0.0.1`, then modify the config/dev.exs to use `username: "$USER" and password: ""`
- There's no project/bin in the phoenix project.
As a workaround, I made `processes.phoenix.exec` cd into the project first before running the create database and start server commands
> docs(phoenix): add example for elixir phoenix

- src/modules/services/mysql.nix
Discussion: https://discord.com/channels/1036369714731036712/1150168934767673505
Currently the following will fail with an infinite recursion:
```
services.mysql.settings.mysqld.port = "${config.env.MY_PORT}";
env.MY_PORT = "1234";
```
This is because `settings` is fully evaluated in order to determine whether to set `MYSQL_TCP_PORT`. It should merely evaluate whether `services.mysql.settings.mysqld.port` exists without evaluating its value.
It is likely that the INI-settings type uses attrsOf instead of lazyAttrsOf.
I'm not fully aware of the consequences of using `lazyAttrsOf` compared to `attrsOf`. Should `lazyAttrsOf` be more common-place for these kinds of settings in general?
> mysql: make settings attrs lazy

- examples/perl/devenv.nix
- examples/perl/devenv.yaml
- src/modules/languages/perl.nix
packages can be literal CPAN package names or nixpkg names like TextCSV.
> perl: Add support for packages attribute.

- src/devenv/cli.py
Currently whenever the python-rewrite of devenv is used on a <1.0 version project it shows the following output:
```
direnv: loading ~/tmp/devenv-experiment/.envrc
direnv: loading https://raw.githubusercontent.com/cachix/devenv/d1f7b48e35e6dee421cfd0f51481d17f77586997/direnvrc (sha256-YBzqskFZxmNb3kYVoKD9ZixoPXJh1C9ZvTLGFRkauZ0=)
direnv: using devenv
direnv: .envrc changed, reloading
error:
error: flake 'git+file:///home/bob.vanderlinden/tmp/devenv-experiment' does not provide attribute 'packages.x86_64-linux.devenv.cachix', 'legacyPackages.x86_64-linux.devenv.cachix' or 'devenv.cachix'
✖ Following command exited with code 1:
/nix/store/bnbhch04awczibxch0qg4lbc3aksrcvw-nix-devenv-2.18.0/bin/nix --show-trace --extra-experimental-features nix-command --extra-experimental-features flakes …
```
> python-rewrite: remove cachix error

- devenv.nix
- examples/fly.io/hello.py
- src/devenv/cli.py
- src/devenv/log.py
- src/devenv/yaml.py
Currently it isn't clear what formatting should be used in the Python files. Since the CLI is now being rewritten to Python could help developers to know how the code should be formatted and format it automatically on pre-commit.
> python-rewrite: use black for code formatting

- src/modules/services/postgres.nix
Fix case in user message printed when DB is already initialized
> postgres: fix case in user message

- src/modules/services/postgres.nix
- src/modules/top-level.nix
This is functionally the same as #844 but for the `python-rewrite` branch.
> [FEAT] Conditionally link devenv profile for python-rewrite

- src/modules/languages/standardml.nix
This adds the `languages.standardml` module for Standard ML.
> Add Standard ML language

- examples/mkcert/devenv.nix
- src/modules/integrations/hostctl.nix
* Adds support for multiple IPs to be configured for one hostname. This is specially important if you want to configure both `127.0.0.1` and `::1` to be the resolution for the same hostname (e.g `example.com`).
I'd highlight that this PR adds support for multiple IPs (as a list of strings) but it also supports the original approach of having just a string.
In OSes like MacOS, where local dns resolution requires both configurations (otherwise you get a 10s delay on it), this is quite important for performance.
It's my first time coding in Nix language so, please bear with my poor coding skills on it. 😄 
Thank you for your time reviewing my PR and for allowing me to learn with your expertise.
Closes #857
> feat: adds support for multiple IP configurations for one hostname in `hostctl.nix`

- src/modules/containers.nix
Currently OCI images created by `devenv` contain a symlink `/lib -> /nix/store/lf0wpjrj8yx4gsmw2s3xfl58ixmqk8qa-bash-5.2-p15/lib`. The symlink conflicts with `libnvidia-container` because `libnvidia-container` tries to create a file `/lib/firmware/nvidia/525.85.12/gsp_ad10x.bin` while it specifies `O_NOFOLLOW` according to https://github.com/NVIDIA/libnvidia-container/blob/1eb5a30a6ad0415550a9df632ac8832bf7e2bbba/src/utils.c#L523
As a result, `libnvidia-container` will produce the following error when starting a container built from `devenv`
```
mount error: file creation failed: /run/containerd/io.containerd.runtime.v2.task/k8s.io/master-node/rootfs/lib/firmware/nvidia/525.85.12/gsp_ad10x.bin: file exists: unknown
```
This PR makes `/lib` a regular directory, and makes files under `/lib` …
> fix: let `devenv` created OCI images be compatible with `libnvidia-container`

- src/modules/containers.nix
This PR allows multi-layered Docker images described at https://github.com/nlewo/nix2container/tree/9d7f33ef0058f4df4c0912025f43c758a3289d76#:~:text=maxLayers%20(defaults%20to%201)%3A%20the%20maximum%20number%20of%20layers%20to%20create.%20This%20is%20based%20on%20the%20store%20path%20%22popularity%22%20as%20described%20in%20this%20blog%20post.%20Note%20this%20is%20applied%20on%20the%20image%20layers%20and%20not%20on%20layers%20added%20with%20the%20buildImage.layers%20attribute.
> feat: add `containers.<name>.maxLayers` option

- .github/workflows/buildtest.yml
- .github/workflows/pin.yml
Can be triggered manually or via another workflow, i.e. after the build succeeds.
Related #536.
> Pin releases on cachix

- src/modules/services/redis.nix
On WSL, the locale is not set properly, therefore, newer Redis versions don't start. 
I would set it the locale to C, to make it same on any platform and not depend on local locales.
If someone wants something different, they can still configure it
> fix: redis startup on WSL2

- src/modules/services/nginx.nix
This adds support for MIME types to Nginx.
Without it the static files don't work because they are all of type "text/plain".
Closes: #876 
I basically copied it from here: https://github.com/NixOS/nixpkgs/blob/nixos-23.05/nixos/modules/services/web-servers/nginx/default.nix#L571
Is there maybe a better way to use configs from NixOS?
This way we just duplicate a lot of the code and I don't really know what else might be useful.
I just noticed the MIME types because my project was broken without them.
> Add defaultMimeTypes to Nginx

- examples/elasticmq/.test.sh
- examples/elasticmq/devenv.nix
- examples/elasticmq/devenv.yaml
- src/modules/services/elasticmq.nix
[Amazon SQS](https://aws.amazon.com/sqs/) compatible solution was asked at the [SymfonyCon Brussels](https://live.symfony.com/2023-brussels-con/) for Devenv. So we quickly added this after the Talk this to Devenv :)
> elasticmq: init

- flake.nix
Add a default overlay for `devenv`.
**Use Cases**
Adding an overlay to `nixpkgs`:
```nix
import nixpkgs {
...
overlays = [ devenv.overlays.default ];
};
```
Override packages in `home-manager`:
```nix
nixpkgs.overlays = [ devenv.overlays.default ];
```
> feat: Add a default overlay

- templates/simple/flake.nix
Without the fix, the examples in the devenv tutorial won't work.
> fix for bitrot in flake template; devenv up requires processes.run.exec

- templates/simple/.envrc
Fix the filenames of the flake (simple) template.
> templates/simple: fix typo in .envrc

- src/modules/top-level.nix
When devenv.root is "/", devenv.state becomes "//.devenv/state," and similar with devenv.dotfile.  Avoid this by normalizing using builtins.toPath to normalize the path (it strips extra slashes).
This is a fork of the python-rewrite branch, for better or worse.
> normalize paths when root is /

- src/modules/containers.nix
Container startup commands did not work due to quoting of args; we now also evaluate any shell variables in the startup command before executing it.
This patch is against the python-rewrite branch.
> Allow container startupCommand to work

- src/modules/languages/ocaml.nix
findlib is required in order for dune to find the different ocaml packages that are installed. Unfortunately opam (ocaml's package manager) does not work on NixOS. So we need to specify all of the ocaml packages that we want to use in our nix files as well.
---
On a somewhat related note, I should update/add the ocaml example to include [nix-ocaml/nix-overlays](https://github.com/nix-ocaml/nix-overlays) because apparently nixpkgs upstream is somewhat outdated for packages.
> Add ocaml's findlib

- examples/python-poetry/devenv.nix
Requires https://github.com/cachix/devenv/issues/920
The `python-poetry` example is currently failing on the `python-rewrite` branch. The problem is that `LD_LIBRARY_PATH` is not supplied by `packages` anymore, but now is supplied using `languages.python.libraries`. This PR makes that change.
> examples/python-poetry: use python libraries instead of packages

- src/modules/languages/python.nix
- Don't recreate Python venv unless Nix wrapper has changed.
- Don't run pip install -r /nix/store/xxx-requirements.txt unless requirements have changed.
This does not take into account use of ``-r`` in requirements.txt and probably should.
This patch is against the python-rewrite branch.
Supersedes #904
> Recreate Python venv and run pip install less often

- src/devenv/cli.py
On the python-rewrite branch.
To allow 'devenv processes stop' to stop processes we need to exec the procfilescript rather than run it as a subprocess.
Without this, no processes will stop.
> fix "devenv processes stop"

- docs/integrations/delta.md
- docs/integrations/difftastic.md
- src/modules/integrations/delta.nix
Hello,
I noticed there was support for difftastic but not delta.  
Delta is an awesome git pager: https://dandavison.github.io/delta/features.html
I actually enjoy it more than difftastic, so I was wondering if it could be a nice addition.
> Add Delta support (a syntax-highlighting pager for git)

- src/modules/languages/python.nix
On python-rewrite branch, put user-defined libraries first on LD_LIBRARY_PATH, so manylinux versions do not block them if the user knows what he's doing.
> Put user libraries first on LD_LIBRARY_PATH

- src/modules/containers.nix
We need to execute the cmd with bash in order to allow "if" and other bash builtins. `exec` replaces bash entirely and these commands aren't on the path.
>  allow builtins (like set and if) within container exec commands

- examples/rabbitmq/.test.sh
- examples/rabbitmq/devenv.nix
- examples/rabbitmq/devenv.yaml
- src/modules/services/rabbitmq.nix
Adds the ability to set a custom node name for rabbitMQ.
This then allows having more than one instance of rabbitMQ running simultaneously in different projects.
> Allow setting rabbitMQ nodeName

- src/modules/services/mysql.nix
I made so that the toggle only affects the CLI user commands and not mysqld itself.
I tried to check for empty settings as well with this:
But it complains about `settings` being a set instead of a boolean, is there a way to check if a set is empty?
I only found ways to check if it has an attribute but I don't think there is an attribute that is always there when some adds custom settings.
```
configFile = if cfg.settings then format.generate "my.cnf" cfg.settings else "";
```
@shyim 
Closes #973
> Add an option to toggle defautls-extra-file for mysql cli commands

- src/modules/services/mysql.nix
I just noticed that I had a typo in the new option.
> Correct typo in option useDefaultsExtraFile

- docs/reference/options.md
- src/devenv/cli.py
- src/modules/containers.nix
- src/modules/languages/python.nix
- Container environments will now have a "user" user.
- The "user" user will have a home dir at `/env`.
- All devenv files (the files referenced by `containers.<name>.copyToRoot`) will now end up in `/env` and will be owned by "user".
- The /nix/store will now be owned by the `user` user.
- `/env` is now the DEVENV_ROOT when within a container.
- the shell in a container environment is now `bashInteractive`, which respects up arrow, down arrow, search, etc.
- The default user in a container environment shell is now the "user" user. 
-  The "user" user will now run all processes and services.
- The max number of layers (a `nix2container` feature) is now an option. 
I'm still a bit unsure whether the permissions of the resulting /env files are the best we can do, but I think so.  They are …
> Nonroot containers

- examples/aws-vault/devenv.nix
- examples/aws-vault/devenv.yaml
- src/modules/integrations/aws-vault.nix
- src/modules/languages/terraform.nix
The following wrapper makes it more convenient to call `terraform` without the need of specifying the `AWS_PROFILE` environment variable or prefixing commands with `aws-vault exec`.
> Implement `aws-vault` integration

- src/modules/languages/rust.nix
Fixes #845, I confirmed the invalid flag-conversion is fixed and the cargo example that I provided is working at macOS.
`'[-L' 'framework=/nix/store/fpvjkq98ylmpp5gkzym4mss1w0s0ji77-devenv-profile/Library/Frameworks]'` is now `-L framework=/nix/store/fpvjkq98ylmpp5gkzym4mss1w0s0ji77-devenv-profile/Library/Frameworks`
> [Rust] Fix: flag conversion was invalid so use string instead of array of string

- examples/aws-vault/devenv.nix
- src/modules/integrations/aws-vault.nix
- src/modules/languages/opentofu.nix
aws-vault integration is failing on CI, and probably has been since https://github.com/NixOS/nixpkgs/commit/6608f1624a8dd9d001de8fc24baa9a2d929b0e82 got merged (Terraform changed its license to the unfree BSL 1.1).
I added a comment on how to get aws-vault to work with terraform by adding `allowUnfree: true` to `devenv.yaml`, but also added the Open Source fork [OpenTofu](https://github.com/opentofu/opentofu) and a wrapper for it in aws-vault, in case people want to switch to it.
> Add OpenTofu and use as default for aws-vault

- .github/workflows/deploy-devcontainer-image.yml
- devcontainer/Dockerfile
This should solve a bunch of issues:
solves https://github.com/cachix/devenv/issues/865 (on a new tag the corresponding devcontainer will be created both tagging the tag version and `latest` i.e. `ghcr.io/cachix/devenv:v.X.X.X` and `ghcr.io/cachix/devenv:latest`)
solves https://github.com/cachix/devenv/issues/680 (this is a multiplatform docker image build for amd and arm)
partially solves https://github.com/cachix/devenv/issues/430 (building and using devcontainer on MacOs especially arm processor now works without issue)
----
I assume we'll also need to retroactively at least generate a devcontainer image for v0.6.3:
https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#authenticating-with-a-personal-access-token-classic …
> build multiplatform devcontainer image on release tag

- examples/rubyonrails/.test.sh
- examples/rubyonrails/devenv.nix
- package.nix
- src/modules/services/postgres.nix
This includes several fixes that I ran into while trying to make the `rubyonrails` example pass the test.
I also ran into postgres unix socket path being too long, but that's already covered by https://github.com/cachix/devenv/pull/1008.
> Fixes to pass rubyonrails test

- examples/phoenix/devenv.nix
`devenv shell` should not prompt the user for (y/n) questions.
> docs(phoenix): remove interactive prompt from devenv shell init script

- devenv/src/main.rs
This PR fixes the issue where when `devenv` was initialized in a project directory that already contained a `.gitignore` file, `devenv` would throw an error, which is counterintuitive since sometimes people want to convert their old projects  to use `devenv` which generally contains a .gitignore.
> fix: Append devenv/devenv/init/.gitignore to an existing .gitignore file in a project instead of baililng out

- examples/terraform/.test.sh
- examples/terraform/devenv.nix
- examples/terraform/devenv.yaml
- src/modules/languages/terraform.nix
This PR follows the pattern of `languages.python` to allow for easy version selection in the Terraform language module using [stackbuilders/nixpkgs-terraform](https://github.com/stackbuilders/nixpkgs-terraform).
> feat: Add support languages.terraform.version

- src/modules/languages/fortran.nix
This PR adds support for fortran language in devenv project:
The following language features are added:
1. A default fortran compiler `gfortran` with an option to use your own version from nix repository
2. `fortran-fpm` a popular fortran package manager
3.  `fortran-language-server` LSP support for fortran.
> feat: Add fortran language support

- devenv.nix
- examples/python-directory/.gitignore
- examples/python-directory/.test.sh
- examples/python-directory/devenv.nix
- examples/python-directory/devenv.yaml
- examples/python-directory/directory/pyproject.toml
- examples/python-poetry/devenv.nix
- examples/python-poetry/devenv.yaml
- examples/python-poetry/pyproject.toml
- src/modules/languages/python.nix
Recently I continued using devenv for various different projects at work, so the need to have it also manage multi-language development environments got bigger.
For a lot of projects, the structure looks similar to the following.
```
project
├── backend
├── devenv.lock
├── devenv.nix
├── devenv.yaml
└── frontend
```
In this example `backend` would for example be the subdirectory of some Python/Django component and then there would be the `frontend` subdirectory e.g. some JavaScript/Node.js component.
For that reason I would like to specify a subdirectory for the individual components.
In this PR I made the necessary changes to be able to specify a working directory via `languages.python.directory`.
While it is already possible to pass paths of requirements files to install dependencies …
> Add options to Python language module

- devenv/init/.envrc
- examples/simple/.envrc
- examples/supported-languages/.envrc
The current version of `.envrc`, which is used by `devenv init`, refers to an outdated version of `direnvrc`. I did not check the differences between the versions but assumed, that the newer one should be provided for the users of the `init` command.
BTW: Very nice tool. I like it very much.
> Updated source_url in .envrc

- devenv/src/main.rs
Add missing documenatation URL to `devenv processes` command help output.
> processes: add documentation url to processes help output

- devenv/src/main.rs
Add missing new line to `devenv up` log output.
Original output:
```
• Building processes ...
• Using Cachix: devenv
✔ Building processes in 1.1s.
• Starting processes ...• Building shell ...
✔ Building shell in 0.7s.
```
New output:
```
• Building processes ...
• Using Cachix: devenv
✔ Building processes in 1.1s.
• Starting processes ...
• Building shell ...
✔ Building shell in 0.7s.
```
> up: add missing new line to log message

- docs/community/contributing.md
Add instructions for creating development projects which can be handy to test changes in modules.
> docs: add instructions for creating dev project

- devenv/src/command.rs
This PR adds a recommendation to use the `-k` flag when invoking `launchctl kickstart` to ensure that the Nix daemon is launched even if it is already running.
For context: while bootstrapping a new machine running MacOS today I ran into a small issue when setting up Nix + devenv. Specifically I installed Nix using the Determinate Systems installer then ran into an error when first running devenv since my user was not in the `trusted-users` list. When I used the suggested command I kept getting the same error since the Nix daemon had not actually been restarted which led me to try with the additional `-k` flag. I'm fairly new to MacOS, but from what I can tell on the launchctl docs this additional flag is required to actually restart the service.
> Update restart Nix command for macOS to include -k flag

- docs/guides/using-with-flake-parts.md
Fixes a non working example in the docs
> docs: Fix undefined variable in minimal flake-parts example

- src/modules/services/mysql.nix
- tests/mysql/.test.sh
- tests/mysql/devenv.nix
@M-arcus and I encountered an issue when working with the mysql and mysqladmin scripts. This was caused by command line arguments not being passed to the underlying mysql binaries.
This PR therefore fixes #1007 
I also updated the mysql tests, because they didn't wait for the configure-mysql process to finish and didn't test for the issue described above.
> Pass command line arguments to mysql scripts

- examples/rubyonrails/devenv.nix
The tests now seem to run inside a pure environment and tests were failing with strange errors.
Initially I worked through the `gem install rails` failures by installing the failing gems individually. This worked, but lead me to a failure from `railties` which [required `git` to be available](https://github.com/rails/rails/blob/6f0d1ad14b92b9f5906e44740fce8b4f1c7075dc/railties/lib/rails/generators/app_base.rb#L733). After adding `git`, it seemed that installing the individual gems wasn't needed anymore, so I removed those statements. Let's :crossed_fingers: something in my environment hasn't made the test succeed by accident.
Lastly, the test itself uses curl to fetch the version from rails, so this package is also added.
I tested this using:
```
git clean -xdf examples/ && nix build && …
```
> examples/rubyonrails: make test pass

- src/modules/top-level.nix
Fixes #567
```nix
{ pkgs, ... }: {
stdenv = pkgs.stdenvAdapters.useMoldLinker pkgs.stdenv;
}
```
> Allow overriding stdenv

- devenv/src/command.rs
- tests/impure/devenv.nix
> Fix the `impure` option

- docs/containers.md
Just a small documentation addition for setting up linux builders on Darwin that hopefully some will find useful if they don't already know about it.
The Darwin module allows for easy linux-builder setup with a 1 line enable through:
`nix.linux-builder.enable = true;`
> docs: nix-darwin linux-builder module link

- src/modules/containers.nix
According to https://github.com/opencontainers/image-spec/blob/main/config.md:
> Entries are in the format of `VARNAME=VARVALUE`. These values act as defaults and are merged with any specified when creating a container.
The `VARVALUE` part does not understand shell escape or quotes.
> fix: `Env` should not be escaped

- src/modules/languages/python.nix
- tests/python-native-libs-uv/.test.sh
- tests/python-native-libs-uv/devenv.nix
- tests/python-native-libs-uv/devenv.yaml
This PR adds an option to enable the [new uv pip drop in replacement](https://github.com/astral-sh/uv) for installing requirements and creating a virtual environment.
> add-uv-pip-replacement

- devenv.nix
- docs/assets/extra.css
- docs/assets/output.css
- docs/overrides/home.html
- package-lock.json
- package.json
- postcss.config.js
- tailwind.config.js
- Rescaled the Tailwind classes to work with mkdocs' 20px base font-size. `text-base` is now 16px (as it should be) instead of 20px.
- Fixed the random "Home" element at the end of the home page.
- Switch to console/shell highlighting for console output.
- Added a shell prefix to the console examples.
- Moved homepage scripts to the scripts block.
- Moved homepage css to the styles block.
- Updated the tailwind setup to fix an issue where unused styles were not being removed.
> docs: update home page

- src/modules/languages/python.nix
Fix regression introduced by https://github.com/cachix/devenv/commit/6ff0c3a81ccbf79f00b5f3289f77df21114bd87e where Python venv will always be recreated unconditionally even if there is no reason to do so.
> fix 1.0.4 regression: python venv always recreated

- flake.lock
- flake.nix
Hi! This is a PR in response to #1122.
I have specified some additional `inputs.follows` rules to de-duplicate shared dependencies.
devenv is still pulling three copies of nixpkgs into the lockfile. One is the actual input, the other two are used for regression tests by `nix` and `pre-commit-hooks` respectively. They should never be instantiated and downloaded, so I have chosen to leave them in, but you could also make the argument that they 'pollute' the lockfile and should be overriden as well. I'd be happy to change that.
Unfortunately, I was unable to resolve what I consider to be the biggest problem: devenv pulling in another copy of itself. Right now, devenv 1.0 includes a reference to the main branch of cachix, which includes a reference to the `python-rewrite` branch of devenv. …
> Deduplicate some Flake inputs

- docs/services.md
This PR adds a bit of extra documentation about starting services in the background.
> docs: add section about starting services in the background

- src/modules/integrations/pre-commit.nix
The packages defined by languages should take priority over the ones loaded by pre-commit. This pushes any `enabledPackages` to the end of PATH.
Language modules should still manually override the pre-commit packages to keep things in sync.
Fixes #1103.
> pre-commit: don't let hook packages override language ones

- examples/phoenix/.test.sh
- examples/phoenix/README.md
- examples/phoenix/devenv.nix
issue: https://github.com/cachix/devenv/issues/1088
reference: https://github.com/cachix/devenv/pull/803/files
<details>
<summary>
tested on nixos@23.11
</summary>
```shell
$ ./result/bin/devenv-run-tests --only phoenix examples
Running in directory examples
Running phoenix
• Overriding .devenv to .devenv.BjsnRDLkJDdy
• Building tests ...
• Using Cachix: devenv
✔ Building tests in 2.0s.
• Building processes ...
✔ Building processes in 18.7s.
• Starting processes ...
• Building shell ...
✔ Building shell in 18.5s.
• PID is 471594
• Stop:      $ devenv processes stop
✔ Starting processes in 18.5s.
• Running tests ...
• Building shell ...
* creating /home/user/.mix/archives/hex-2.0.6
✔ Building shell in 1.7s.
* creating /home/user/.mix/elixir/1-15/rebar3
15:29:53.674 [notice] Application hex …
```
> docs(phoenix): connect to unix socket instead of tcp

- devenv.nix
- templates/flake-parts/.envrc
- templates/flake-parts/flake.nix
Let `.envrc` generate the `devenv.root`
> Avoid --impure in flake-parts based projects

- Cargo.lock
- Cargo.toml
- devenv-run-tests/Cargo.toml
- devenv/Cargo.toml
- devenv_core/Cargo.toml
- devenv_core/src/lib.rs
This will be filled out in another PR to move some functionality from the devenv package so that it can be used in devenv-test-all.
> Create the devenv_core package

- src/modules/top-level.nix
Use the `no-dereference` option to stop `ln` from following the existing `.devenv/run` symlink and creating a recursive symlink inside the runtime dir to itself.
Fixes #1115.
> Fix infinite symlinks in runtime dir

- src/modules/languages/c.nix
We already add `stdenv`, which contains all the compilers and sets up the `CC` and `CXX` env variables for each platform. Adding `clang` or `gcc` on top can result in the wrong compilers being set up for the current platform, e.g. gcc on macOS. We saw this happen when building native extensions in ruby.
I imagine this broke once we switched back to `nix develop`.
Also, this might fix the macos ruby tests 👀
Fixes #966.
Fixes #965.
> c: fix an issue where the wrong c/cpp compiler could be set up

- src/modules/languages/rust.nix
Should we use mold by default to speed up compilation?
> rust: use mold

- templates/flake-parts/flake.nix
- templates/simple/flake.nix
Fixes #1027.
Fixes half of #1153.
~Also, updated all the templates to use `devenv/latest`, instead of `main`.~
> Fix flake-parts template

- examples/rust-wasm-cross/.test.sh
- examples/rust-wasm-cross/devenv.nix
- Fix the linker issue on macOS. Link to upstream issue.
- Fix the build on `aarch64-linux`, where `wasm-pack` complains that it can't load a build of `wasm-opt`.
> rust-wasm-cross: fix darwin and aarch64-linux builds

- .github/workflows/generate.yml
- Cargo.lock
- devenv.yaml
- devenv/Cargo.toml
- devenv/init/devenv.yaml
- devenv/src/config.rs
- docs/devenv.schema.json
Superseeds https://github.com/cachix/devenv/pull/598 by generating it.
> add devenv.schema.json

- devenv/src/main.rs
```console
➜ devenv shell --help
Activate the developer environment. https://devenv.sh/basics/
Usage: devenv shell [CMD] [ARGS]...
Arguments:
[CMD]
[ARGS]...
Options:
-h, --help  Print help
```
```console
➜ devenv shell --help
Activate the developer environment. https://devenv.sh/basics/
Usage: devenv shell [OPTIONS] [CMD] [ARGS]...
Arguments:
[CMD]
[ARGS]...
Options:
-v, --verbose
Enable debug log level.
-j, --max-jobs <MAX_JOBS>
Maximum number of Nix builds at any time. [default: 4]
-s, --system <SYSTEM>
[default: aarch64-linux]
-i, --impure
Relax the hermeticity of the environment.
--offline
Disable substituters and consider all previously downloaded files up-to-date.
-c, --clean [<CLEAN>...]
Ignore existing environment variables when entering the shell. Pass a list of comma-separated …
```
> devenv: make common CLI options global

- devenv/src/command.rs
Fix for #1024 -- enables the usage of the cachix env var.
Note, this does *not* support the netrc, as that would seemingly be more complicated
```
$ ~/projects/devenv/result/bin/devenv test
• Overriding .devenv to .devenv.HbfeKKcHpORj
• Building tests ...
• Using Cachix: devenv, private
• Trusting private.cachix.org on first use with the public key private.cachix.org-1:blabla
✔ Building tests in 11.2s.
```
> feat: support private caches

- docs/guides/using-with-flakes.md
Running `devenv up` with the current instructions fail with:
```
error: flake 'git+file:///...' does not provide attribute 'packages.x86_64-linux.devenv-up', 'legacyPackages.x86_64-linux.devenv-up' or 'devenv-up
```
> Fix instructions for usage with flakes

- src/modules/languages/javascript.nix
This fixes yarn using a different nodejs version (partially solves https://github.com/cachix/devenv/issues/637). This doesn't work if yarn pkg is a `nodePackage`. Pnpm also has the same problem since it's a `nodePackage`, not sure how to fix that, seems to use the first node version that is installed.
> Fix: sync nodejs versions

- src/modules/languages/odin.nix
This pull request adds support for https://odin-lang.org/, with `package` and `debugger` options. By default `gnumake` `ols`, `clang` and `nasm` packages are included.
resolves #888
> feat: add odin language support

- examples/process-compose/devenv.nix
- examples/python-django/devenv.nix
AFAIKT `process_ready` is not a thing. 
https://f1bonacc1.github.io/process-compose/launcher/#define-process-dependencies
> examples: rename `process_ready` to `process_healthy`

- src/modules/languages/rust.nix
Adds an assertion to guide users to use the fenix channels when using targets.
Resolves #1223.
> rust: assert that targets are not used with nixpkgs channel

- src/modules/integrations/dotenv.nix
- tests/dotenv/.setup.sh
- tests/dotenv/.test.sh
For example, `export FOO=1`.
Fixes #1207.
We can't use non-capturing groups, so this is the best I could come up with.
I couldn't find a spec for the .env format. But some of the parsers support multiline strings, escape quotes, and what not. That's going to be rough to do inside Nix...
> dotenv: support export declarations in .env files

- src/modules/top-level.nix
Fixes #1153.
`nix develop` sets `TMPDIR` which changes the computed runtime dir between creating the shell and running `devenv up`.
`DEVENV_RUNTIME` changes from `/tmp/devenv-<hash>` to `/tmp/nix-shell.<hash>/devenv-<hash>`.
This makes the flake-based `devenv up` error out because process-compose expects the runtime dir to exists when creating the unix socket.
Non-flake `devenv up` is not affected by this, as it seems to create the new runtime dir before running the procfile.
On NixOS, this error doesn't show up because `XDG_RUNTIME_DIR` is set by default and is used as the `tmpdir`. This is not touched by `nix develop`.
> Reuse `DEVENV_RUNTIME` to work around `nix develop` modifying `TMPDIR`

- src/modules/containers.nix
We shouldn't inherit them from the current shell.
IMHO when/if we move away from flakes, we should do this on the rust side.
Fixes #1182.
> container: override tmpdir and runtime dir

- .github/workflows/generate.yml
- devenv.nix
- src/modules/integrations/hostctl.nix
- src/modules/languages/php.nix
- src/modules/languages/python.nix
- src/modules/languages/rust.nix
- src/modules/processes.nix
- src/modules/services/caddy.nix
- src/modules/services/couchdb.nix
- Commit missing generated docs and schema in CI
- Make doc generation idempotent to the environment where it runs. This means removing any reference to local directories and hashes from the defaults and examples.
- Added a read-only `baseDir` to couchdb to make it easier to reference the location of its state when overriding settings.
> docs: commit docs in CI and make doc generation idempotent

- devenv/src/config.rs
- devenv/src/main.rs
Fixes #1049.
There are two commits to this:
1. Removing null attributes when serializing the flake input struct. This fixes #1049.
2. Validating that only one of `url` and `follows` are set.
2 is a little controversial because Nix actually allows setting both `url` and `follows` at the same time. The following example will not trigger an error in Nix:
```nix
{
nixpkgs = {
url = "...";
follows = "other-input/nixpkgs";
};
}
```
Nix seems to implicitly prioritise `follows` over `url`, which could be quite confusing. Our choice is whether to do better than Nix in this situation and throw a descriptive error, or allow it through and let Nix decide what's best.
> Allow follows in top-level inputs and validate flake inputs

- examples/scripts/devenv.nix
- src/modules/scripts.nix
> feat(scripts): allow custom interpreters

- docs/languages-all.md
- examples/solidity/.test.sh
- examples/solidity/devenv.nix
- examples/solidity/devenv.yaml
- src/modules/languages/solidity.nix
This PR:
- adds support for Solidity (`languages.solidity`, https://soliditylang.org/) with `package` option. Default `package` is `pkgs.solc` from `nixpkgs`.
- adds support for Foundry (`languages.solidity.foundry`, https://book.getfoundry.sh/) with `package` option. Default `package` is `foundry-bin` from [foundry.nix](https://github.com/shazow/foundry.nix).
If you want to try this out, you will need to change your `devenv.yaml`:
```yaml
inputs:
devenv:
url: github:gabr1sr/devenv/new/modules/solidity?dir=src/modules
foundry:
url: github:shazow/foundry.nix
inputs:
nixpkgs:
follows: nixpkgs
```
And change your `devenv.nix`:
```nix
{ ... }:
{
languages.solidity = {
enable = true;
foundry.enable = true;
};
}
```
Related to shazow/foundry.nix#34
> add: solidity and foundry support

- devenv.nix
- src/modules/scripts.nix
Adds the script's description and its path to the output of `devenv info`.
Preview for devenv:
```shell
- docs: exec /nix/store/1vi1k0wy7a86g8i5imypw1p2g1g2bjl9-docs
- tailwind: exec /nix/store/ln9gvm1gkmii8bxr51n4r54c8j1w3991-tailwind
- devenv-generate-doc-options: Generate option docs.
/nix/store/f3kp77kfxl08nqlpzdmkykqnf1cwnfhc-devenv-generate-doc-options
- devenv-generate-docs: Generate lists of all languages and services.
/nix/store/ycwim9lpm0azqkh77sysr3j2kw17m5fc-devenv-generate-docs
- devenv-generate-languages-example: Generate an example enabling every supported language.
/nix/store/17x10g90jicnadi2ixm5as2gd9ch6vi6-devenv-generate-languages-example
- devenv-test-cli: Test devenv CLI.
/nix/store/jiyllnk1sm3bamhrkbh38lhhh5svhqij-devenv-test-cli
```
Suggested by @karfau on discord.
> info: print the script description and path in `devenv info`

- src/modules/languages/c.nix
This PR adds `gdb` and `valgrind` to the list of default packages, which are important tools for developing with C.
> Add debugger tools to C language pack 

- package-lock.json
Compiling devenv results in a `npm` error message referencing [CVE-2024-4068](https://github.com/advisories/GHSA-grv7-fg5c-xmjg). This PR addresses this and bumps the braces to v3.0.3 which serves as a potential fix for it.
> chore: bump braces to 3.0.3 to fix CVE-2024-4068

- src/modules/process-managers/process-compose.nix
Serialize the tui boolean to "true" and "false", instead of "1" and "".
> process-compose: fix an error when disabling the tui

- src/modules/services/caddy.nix
I have a project example path of `/home/user/coding/my projects/devenv-project`.
When running `devenv up` the caddy logs show:
`/nix/store/2diacl69qsxagwr73f1ykc5j750sln0j-caddy: line 2: projects/devenv-project/.devenv/state/caddy/data: No such file or directory`
caddy tries to use `projects/devenv-project/.devenv/state/caddy` as dataDir instead of `/home/user/coding/my projects/devenv-project/.devenv/state/caddy`.
This PR quotes the `XDG_*_HOME` paths so they can also contain spaces.
> fix: allow caddy dataDir with spaces

- devenv/src/command.rs
While compiling devenv on NixOS, I noticed that the instructions for using cachix were only provided for non-NixOS distributions. This PR addresses this issue and adds documentation for NixOS.
> docs: Add instructions to use cachix on nixos

- devenv-run-tests/src/main.rs
This probably got lost in all the rebases.
> devenv-run-tests: override the devenv input

- examples/trafficserver/.test.sh
- examples/trafficserver/devenv.nix
- src/modules/services/trafficserver/default.nix
- src/modules/services/trafficserver/ip_allow.json
- src/modules/services/trafficserver/logging.json
- src/modules/services/trafficserver/update.sh
Creates a new module for [Apache Traffic Server](https://trafficserver.apache.org).
> trafficserver: new module

- tests/postgres-pghost/.test.sh
- tests/postgres-pghost/devenv.nix
This PR adds a test for examining the anomalies when we set the `listen_address/PGHOST` value to "*". The expected result is this test failing on macos based systems as described in this [this](https://www.postgresql.org/message-id/1860173.1719520971@sss.pgh.pa.us) forum
ref  #1298
> test: postgres PGHOST and listen_address test

- src/modules/languages/python.nix
The `--upgrade-dep` flag was introduced in python version `3.9`, this PR disables the flag in case of python version lower than the version `3.9`
fixes #1289
> fix: --upgrade-dep not available with python < 3.9

- devenv/src/command.rs
Fixes the `cachix watch-exec` command. 
Also pretty-prints the command if `run_nix` fails to make it easier to track down which command is failing in the future.
Fixes #1311.
> devenv: fix the cachix integration

- devenv.nix
The base `devenv.nix` configuration relied on NPX to execute Tailwind CSS commands. However, for users without Node.js installed locally, these commands would fail. This update replaces NPX with the Tailwind package from Nix, ensuring compatibility regardless of local Node.js installations.
> Bug/tailwindcss - Update devenv.nix to Use Tailwind Nix Package

- src/modules/services/postgres.nix
> Assign PGHOST to runtimeDir as default 

- .cargo/config.toml
- .gitignore
- Cargo.lock
- Cargo.toml
- devenv/Cargo.toml
- devenv/src/cli.rs
- package.nix
- xtask/Cargo.toml
- xtask/src/main.rs
- xtask/src/manpage.rs
Usage:
```shell
cargo xtask generate-manpages --out-dir OPTIONAL_PATH
```
> devenv: generate and ship manpages

- devenv/src/cli.rs
- devenv/src/command.rs
I was using devenv as flake library but later switched to cli, only noticing that is magnitude slower. What is the main reason for disabling caching? 
Without caching:
```
time devenv shell exit
• Building shell ...
✔ Building shell in 5.1s.
0.76s user 0.18s system 13% cpu 7.154 total
```
With caching:
```
time devenv --eval-cache shell exit
• Building shell ...
✔ Building shell in 1.5s.
0.06s user 0.03s system 5% cpu 1.645 total
```
> Allow caching

- Cargo.lock
- package.nix
- xtask/Cargo.toml
- xtask/src/cli.rs
- xtask/src/lib.rs
- xtask/src/main.rs
- xtask/src/manpage.rs
- xtask/src/shell_completion.rs
Build-time generated shell completions.
```shell
cargo xtask generate-shell-completion <SHELL> --out-dir <OPTIONAL_OUT_DIR>
```
> devenv: add shell completions

- docs/overrides/home.html
Noticed this while browsing the home page, bumps the count like https://github.com/NixOS/nixos-search/pull/756 does.
> home: bump packages count

- templates/flake-parts/.envrc
The flake-parts template's `.envrc` erroneously refers to files (`devenv.nix`, `devenv.lock`, `devenv.yaml`that are not present for that kind of setup. It should point to the ones that are really there
> make flake-parts .envrc match .nix and .lock files

- src/modules/languages/clojure.nix
This PR adds the functionality of selecting the `jdk` version for `clojure` programming language using overrides.
Fixes #1341
> feat: Add option to select jdk with clojure

- src/modules/services/mysql.nix
This PR addresses an issue in `MySQL` or `MariaDB` where attempts to assign a password to the root user are unsuccessful, resulting in the default `blank` password being used.
Fixes #1251
> fix: Root user password assignment in MySQL and MariaDB

- docs/getting-started.md
Simply changed the current tip to be a little clearer for people who might mistake the current instruction to mean upgrade via rerunning the install instruction.
"Follow the instructions for an installation above."
to
"To update, refer to the specific upgrade instructions provided in the documentation for the installer you used from the options above. "
> Update documentation for devenv upgrades tip

- src/modules/cachix.nix
- src/modules/languages/nix.nix
**This fix saves 7 GB** in the closure size of my devenv projects which have Nix language support enabled.
Background: Currently, with `languages.nix.enable = true;`, all outputs of the `cachix` package in Nixpkgs get installed. Unlike the Cachix package provided by the [cachix/cachix](https://github.com/cachix/cachix) flake, this is a massive multi-output derivation that includes a huge Haskell runtime with libs in `.out` and more than a gigabyte of library documentation in `.doc`.
The original issue here raises some questions for me about how devenv profiles are constructed and whether they do or should honor `meta.outputsToInstall`-- maybe there's something to think about there, too. (The Cachix package in nixpkgs has only `"bin"` in `meta.outputsToInstall`.)
Anyway, this fix works now …
> Nix language support improvements, including smaller Cachix

- flake-module.nix
This PR adds an option `devenv.modules` which takes an array of module types (paths, functions and attrsets) and forwards them into all shells.
That makes it way easier for flake modules (when using flake-parts) to add custom options for shells.
For example, it would allow my [nix-devtools](https://gitlab.com/TECHNOFAB/nix-devtools) to easily add task and teller integration without the user having to add `imports` into every shell. (see `feat/flakeModule` for example)
> feat: add `modules` option to allow flakeModules to add options to every devshell

- src/modules/languages/python.nix
@domenkozar This does work for me.
However, there are no tests.
Further, being a devenv newbie, I have no idea how many best practices I am breaking.
> python: when enabling uv and venv, version is not respected

- examples/rust-wasm-cross/devenv.nix
- examples/rust/.test.sh
- src/modules/languages/rust.nix
Remove `darwinFlags` to fix linking error when compiling no_std crate. Closing #1355 
Only tested with Developer Frameworks already installed in the system.
I am not sure if this change will break those who only rely on Developer Frameworks in Nixpkgs and don't have Developer Frameworks installed outside Nix.
> Remove darwinFlags in rust module

- devenv.nix
- devenv/src/command.rs
- src/devenv-devShell.nix
`--impure` means both impure evaluate and impure build, while `--no-pure-eval` means impure evaluate and pure build.  `--no-pure-eval` can be used to determine cwd. `--impure`  is more evil and unnecessary in devenv.
> Pass `--no-pure-eval` instead of `--impure`

- src/modules/processes.nix
Fixes #1270.
@domenkozar, should we be deleting the runtime dir when taking down processes? Any good reason to do this?
There are a few issues with this line:
1. It relies on trapping a signal. In the case of process-compose, I think the reason it's immune from this failure is because the trap is never triggered. We need to rethink how we run post-process actions.
2. We create the runtime dir in the CLI, but try to delete it in the shell script. This sounds like a bug magnet to me.
3. There was an issue a while back where redis would crash on shutdown because of a race condition here.
> fix: don't delete runtime dir on process down

- templates/flake-parts/flake.nix
Prevents https://github.com/cachix/devenv/issues/1360, which occurs with the current template if a local flake registry (global, user, whatever) sets `flake-parts` directly to a path under `/nix/store` which is later garbage collected.
That issue seems like a pretty big footgun in its non-obviousness, and it's also a mess to clean up. I think it's probably better not to have any `type: "indirect"` stuff in the default `flake.locks` produced by our flake-parts template. This fix addresses the named issue in just that way.
> flake-parts template: make flake-parts input source explicit

- devenv/src/cli.rs
- devenv/src/devenv.rs
- devenv/src/log.rs
- devenv/src/main.rs
Fixes #435 
This is useful for people who don't want to clutter their terminal with logs. This will also be useful in CI environments for people who want a cleaner log. For example a user can enter a shell without seeing any logs using the following commad.
```sh
devenv -q shell
```
> feat: add a `--quiet` flag to disable logging

- src/modules/languages/scala.nix
This change makes the choice of Scala build tools configurable.
This is a minimal change that's in line with the existing functionality in the Scala module.
> scala: add support for mill (build tool)

- src/modules/services/postgres.nix
This PR resolves (https://github.com/cachix/devenv/issues/1212) by adding a configuration option that enables the user to start the PostgreSQL server with a custom pg_hba.conf file, this file is primarily used to enable or disable which IPs get to connect to the server both locally (from UNIX sockets) or from the network (using TCP/IP).
I had a "Fine I'll do it myself moment" and honestly after I saw the code it wasn't really that hard.
> feat: Added custom option and config

- templates/flake-parts/.envrc
Originally, bash generates `/dev/fd/63` from `"file+file://"<(printf %s "$PWD")` and nix caches the file content with TTL 3600 seconds, as a result, if two flake-parts based devenv projects are created under different paths, they would interfere each other's cache for `/dev/fd/63`, and result in wrong `DEVENV_ROOT`.
This PR disables the nix file cache to avoid the problem.
> fix: let nix not cache bash generated file

- src/modules/services/redis.nix
This fixes the issue where Redis would ignore termination signals from process-compose, as it assumes it is running under systemd and similar PID 0 managers.
> fix: Prevent Redis from remaining running in the background

- docs/reference/options.md
- docs/supported-languages/java.md
- src/modules/languages/java.nix
On nixpkgs, the `jdk` argument has been renamed to `jdk_headless`, currently causing the devenv to fail to build maven with:
```
error: function 'anonymous lambda' called with unexpected argument 'jdk'
at /nix/store/pwwns4fq736wqpmf5xfsxds4kh4f580w-source/pkgs/by-name/ma/maven/package.nix:1:1:
```
See [this commit on nixpkgs](https://github.com/NixOS/nixpkgs/commit/ea0bc3224593ddf7ac6c702c7acb6c89cf188f0f#diff-b3af06f6694c5996094cf6cd4db45398f256ff6e2d56d9a7b1b275092badd7d9)
> Fix maven failing to build with `function 'anonymous lambda' called with unexpected argument 'jdk'`

- src/modules/process-managers/process-compose.nix
> process-compose: fix running processes with `is_elevated`

- src/modules/integrations/aws-vault.nix
- src/modules/integrations/devcontainer.nix
- src/modules/services/couchdb.nix
- src/modules/services/nginx.nix
- src/modules/services/opensearch.nix
- src/modules/services/varnish.nix
Removes the uses of deprecated functions, that is no longer used/removed aliases.
Hopefully this should be fine? I'm not 100% sure that devenv does not follow some older nixpkgs version.
> fix: removed use of deprecated lib functions

- src/modules/containers.nix
These options allow for layer deduplication using the approach described at https://blog.eigenvalue.net/2023-nix2container-everything-once/
> Add `containers.<name>.layers` and `containers.<name>.enableLayerDeduplication`

- src/modules/containers.nix
This PR fixes the following error:
```
The option `perSystem.x86_64-linux.devenv.shells.default.containers.processes.layers."[definition 2-entry 1]".perms."[definition 1-entry 1]".gid' does not exist.
```
> fix: add user/group options used in the container module

- src/modules/containers.nix
Fixes missing home directory when no `copyToRoot`.
```
{
containers.example = {
name = "example";
startupCommand = "bash";
copyToRoot = [ ];
};
}
```
Previous error message
```
✦ ❯ docker run -it example
mkdir: cannot create directory '/env/.devenv': Permission denied
ln: failed to create symbolic link '/env/.devenv/profile': No such file or directory
ln: failed to create symbolic link '/env/.devenv/run': No such file or directory
```
> Allways creating home directory even if nothing in `copyToRoot`

- docs/reference/options.md
- src/modules/services/postgres.nix
- tests/postgresql-customdbuser/.test.sh
- tests/postgresql-customdbuser/devenv.nix
- tests/postgresql-customdbuser/testinitdb.sql
Add user/pass capability to `services.postgres.initialDatabases` because we usually like to test our services with specific DB users. The options are optional, functionality remains the same if not given.
If we now do this:
```nix
services.postgres = {
enable = true;
listen_addresses = "localhost";
port = 15432;
initialDatabases = [
{
name = "pdns";
user = "pdns";
pass = "mypdnssecretpass1234";
schema = ./_testdata; # *.sql in version order
}
];
};
```
the following will happen:
1. `postgres` DB is created as usual, owned by `$USER` (who is SUPERUSER) for this instance)
2. A role `pdns` with password `${pass}` is created
3. Database `${name}` is created
4. All privileges on `pdns` are granted to user `pdns`.
5. The schema seeding scripts in `${schema}` are executed as user `pdns`.
> Improve services.postgres db init

- docs/assets/extra.css
- docs/assets/output.css
- docs/assets/top-level.css
- docs/overrides/home.html
- mkdocs.yml
This PR addresses the website UI anomalies in blog page and also fixes some general bugs related to side navigation bar.
> fix: Website UI bugs

- src/modules/services/redis.nix
Modules should take care not to conditionally set `env` using user-provided input. If the conditional is another `env` value, evaluation will fail with an infinite recursion error.
While the user can often easily break the loop on their end, knowing what to do requires considerable experience with the module system.
Fixes #1440.
> redis: prevent infinite recursion when port is set to an env var

- src/modules/languages/c.nix
Disable `gdb` for `aarch64-linux`.
cc https://github.com/cachix/devenv/pull/1216
> fix: Disable gdb for aarch64-linux

- examples/go/default.nix
- examples/go/devenv.nix
- examples/go/devenv.yaml
This PR adds an example to build go applications.
It adds:
-  the input for gomod2nix
- the output with the example app
feel free to update anything needed or let me know what needs to be changed.
> add go example

- docs/.pages
Might want to keep the other one !
> Doc: remove doubled `Outputs` item in menu

- devenv/src/tasks.rs
Fixes sourcing exported variables with spaces in them. Hello, macOS.
> devenv: escape shell vars in task exports

- docs/reference/options.md
- src/modules/tasks.nix
> fix: add missing task option descriptions

- src/modules/languages/javascript.nix
Inherit a package, so that we do not end up with different versions of Node.js as default is whatever is marked as stable in Nixpkgs.
> Yarn must the same package as language definition.

- src/modules/tasks.nix
> fix: ensure .devenv directory exists for devenv:enterShell task

- src/modules/languages/typescript.nix
Some editors (e.g. helix) benefit from this.
And others won't have to install it themselves
> typescript: add language-server

- devenv-eval-cache/src/internal_log.rs
Again, these are marked as errors and need to be filtered out from the other pile of error-level messages we get back.
> devenv: display trace warnings

- src/modules/processes.nix
This undocumented attr option was removed https://github.com/cachix/devenv/pull/1147. Now that `process.process-compose` itself is gone, people might start running into errors (see https://github.com/cachix/devenv/issues/1497#issuecomment-2397438790) . This adds a migration to the new `process.managers.process-compose.port`.
> process-compose: add a migration for `process.process-compose.port`

- src/modules/languages/javascript.nix
The default node package [was, possibly unintentionally, changed](https://github.com/cachix/devenv/commit/7fce56e5b2eeb36e05a7f534356e9074868e9f82) to `nodejs-slim`, which doesn't ship with npm. This broke the `npm.enable` integration.
If `npm.enable`, we add `languages.javascript.npm.package`. Otherwise, we add `languages.javascript.package`.
This also fixes our pre-commit CI.
> javascript: ensure node build includes npm if `npm.enable`

- devenv-eval-cache/src/command.rs
- devenv-tasks/src/lib.rs
- devenv-tasks/src/main.rs
- devenv/src/cnix.rs
- devenv/src/devenv.rs
- src/modules/languages/javascript.nix
- src/modules/languages/rust.nix
Make sure we don't exit with code `0` if `devenv test` fails.
This requires both a module and a CLI update. On older versions of devenv, the updated tasks runner will cut of a bit of output at the end ("Tests failed :("), as it bails out of the `nix develop` command early.
I would've preferred something like `cmd.run().await?.bail_on_error()`, where we can make the decision to bail on each invocation, but that's a bit too invasive at this time.
Reported on Discord.
> fix: output non-zero code when `devenv test` fails

- docs/reference/options.md
- docs/supported-languages/texlive.md
- examples/texlive/.test.sh
- examples/texlive/devenv.nix
- src/modules/languages/texlive.nix
Docs on the new API: https://nixos.org/manual/nixpkgs/stable/#sec-language-texlive-user-guide-experimental
Though labeled "experimental", it's  been available for a year (since 23.11) and is backwards-compatible with the old `combine` API. Might as well switch over.
Also:
- The default for `base` is now `texliveSmall`. Could use `texliveBase`, but `Small` seems like reasonable default.
- `"collection-basic"` removed from `packages`. The base package set is handled by `base` now. This option can also now be empty if you don't need extra packages.
Fixes #1521.
> texlive: switch to the new `withPackages` API

- devenv/src/cnix.rs
Removes semicolons from the `nix.conf` suggestion and adds back the missing instructions to set `cachix.enable = false` when using os-wide caches on nixos.
> devenv: fixup nixos-specific cache fallback docs

- src/modules/languages/go.nix
Doesn't seem to make sense to have support for go from nixpkgs but then let the go compiler fetch a random toolchain so lets tell it to use the local toolchain always.
> Set GOTOOLCHAIN=local for languages.go

- examples/hivemind/devenv.nix
- examples/overmind/devenv.nix
Was trying to use `overmind` using the example in the repo and got:
```
warning: The option `process.implementation' defined in `<path to my workdir>/deven
v.nix' has been renamed to `process.manager.implementation'. 
```
Fixed the `overmind` and `hivemind` example to follow this hint.
> update process manager implementation examples

- src/modules/languages/javascript.nix
Currently whenever a javascript tool is installed with npm, yarn, pnpm, it is not possible to directly use it:
```
$ npm install vite
$ vite
vite: command not found
$ npx vite
```
This is because `node_modules/.bin` is missing from `PATH`, which this PR adds. I've opted to add it regardless of which package manager of javascript is used nor regardless of whether `node_modules` exists.
> javascript: add node_modules/.bin to PATH

- src/modules/process-managers/process-compose.nix
Reverts cachix/devenv#1465
Mitigates #1569.
The `ncurses` derivation creates recursive symlinks in `includes` that can trip up aggressive file watchers that decide to venture into `.devenv/profile`. Reverting for now until we better understand the process-compose requirements.
> Revert "Add `ncurses` if process-compose's TUI is enabled"

- src/modules/containers.nix
> containers: add `usr/bin/env` to the root layer

- flake-module.nix
Adds support for `devenv test` in `flake-parts`. Continuation of https://github.com/cachix/devenv/pull/1524.
> flake-parts: add `devenv test` support

- src/modules/languages/go.nix
If you set `languages.go.package` to a version of the go compiler that doesn't yet exist in the `nixpkgs` input, you'll get an evaluation error on `buildGoXXXModule` because the function for that specific version doesn't exist.
I couldn't find anything in the docs preventing us from using the base `buildGoModule` and override the `go` argument as we already do.
Fixes #1568.
> go: use non-versioned `buildGoModule` to support out-of-band compilers

- src/modules/services/kafka-connect.nix
- src/modules/services/kafka.nix
- tests/kafka-connect/.test.sh
- tests/kafka-connect/devenv.nix
- tests/kafka/.test.sh
- tests/kafka/devenv.nix
Here is a rough implementation of a kafka service for devenv.
I think there are definetely place for configuration options. but I am not sure how we can implement this properly. So feedback would be appreciated :)
closes #1563
> feat: Added kafka service

- devenv/src/devenv.rs
Currently, when running `devenv init` in a folder that already contains a `.gitignore` file the first line of the additions is written at the end of the last line of the existing file. If the existing file does not end with a newline, the `# Devenv` comment is appened at the end of the line.
Example:
An existing `.gitignore`
```.gitignore
dist
```
(no newline at EOF)
will result in:
```.gitignore
dist# Devenv
.devenv*
devenv.local.nix
.direnv
.pre-commit-config.yaml
```
> fix: ensure append is on newline with existing `.gitattributes`

- src/modules/integrations/android.nix
> fix: typo in description for enabling react native support

- docs/.pages
- docs/guides/.pages
- docs/guides/using-with-flake-parts.md
- docs/guides/using-with-flakes.md
Re-organize and rewrite some sections to make it clearer how to enter the shell and launch processes, services, and tests.
> docs: update flake guides

- flake.nix
This makes it harder to accidentally add the regular devenv CLI to packages and make the flake integration inoperable.
> flake: make it difficult to clobber the flake shim

- devenv-tasks/src/lib.rs
- docs/reference/options.md
- package.nix
- src/modules/integrations/git-hooks.nix
- src/modules/languages/python.nix
- tests/tasks/devenv.nix
~I think we're running the tasks in reverse order after the toposort. The following tasks are speced to run _after_ `enterShell`, but they instead run before.~
This PR lets the graph traversal visit both incoming _and_ outgoing edges.
Traversing all the edges of a node allows picking up tasks that are only specified to run _after_ the current node. For example:
```nix
tasks."my-app:after-venv" = {
exec = "echo hello";
after = [ "devenv:python:virtualenv" ];
};
```
Previously, the only way to do this was to also use `before` to add this dependency to the graph, usually via `devenv:enterShell`. This change also allows running tasks after `devenv:enterShell`.
Fixes #1557.
While this change makes setting up tasks more predictable, we'll need to make this behavior configurable to support …
> tasks: pickup outgoing task dependencies

- Cargo.lock
- Cargo.toml
- devenv/Cargo.toml
- devenv/src/cnix.rs
- nix-conf-parser/Cargo.toml
- nix-conf-parser/src/lib.rs
- package.nix
If devenv cannot configure the requested caches, it displays instructions to either become a trusted user or to set up the caches globally. However, it never checks if the caches are actually configured, so the only solution is to set `cachix.enable = false;`, which can get tedious across many projects.
This PR queries Nix to figure out which caches and keys are missing. If the user is not trusted, but all the caches are already configured, no warning is shown.
> devenv: skip the cache warning if the requested substituters are already configured

- src/modules/languages/nim.nix
Currently set [nimlsp](https://github.com/PMunch/nimlsp) package does not seem to be actively maintained.
The official [Nim Language Server](https://github.com/nim-lang/langserver) seems the defacto standard as now (this what I have been using) (experienced Nim users please comment).
> feat(nim): switch to official lsp

- devenv/src/cnix.rs
- devenv/src/devenv.rs
- Reduce writes to `.devenv.flake.nix` to make it viable to be watched for changes by direnv.
- Track `.devenv.flake.nix` to captures changes to other flake inputs, like TMPDIR and PWD. Changes to these should cause cache invalidation.
- Sort command arguments to avoid cache misses stemming from non-deterministic ordering.
> devenv: caching fixes and improvements

- devenv/src/devenv.rs
- src/modules/containers.nix
I was looking to deploy a container built by devenv to fly.io, and found that configuring registry auth through `defaultCopyArgs` like in the docs or example didn't work. I had to specify it through `--copy-args` on the command line.
https://github.com/cachix/devenv/blob/4b8677f62022e6a235cc4e93a6bbc3d57b77817f/docs/containers.md?plain=1#L143-L149
The `copy-container` script determines whether to use `defaultCopyArgs` by looking at the remaining number of script arguments after consuming the first and second arguments:
https://github.com/cachix/devenv/blob/4b8677f62022e6a235cc4e93a6bbc3d57b77817f/src/modules/containers.nix#L175-L179
However, the `copy` command always invokes the script with three arguments:
https://github.com/cachix/devenv/blob/4b8677f62022e6a235cc4e93a6bbc3d57b77817f/deve …
> Fix defaultCopyArgs always getting ignored

- src/modules/top-level.nix
`nix develop` overrides all of the temp directories, which causes problems for module evaluation after the shell, for example `devenv up`.
The temporary `nix-shell-<hash>` directory it creates is also unsafe to use as it might be garbage collected at a later point.
The previous solution was to pick up the `DEVENV_RUNTIME` var, but that is not safe for nested devenvs and does not solve the the tmpdir issue.
Fixes #1620.
> devenv: override temp dirs after nix develop

- .envrc
- Cargo.lock
- devenv/Cargo.toml
- devenv/init/.envrc
- devenv/src/cli.rs
- devenv/src/devenv.rs
- devenv/src/flake.tmpl.nix
- devenv/src/lib.rs
- devenv/src/main.rs
- direnvrc
- docs/automatic-shell-activation.md
- docs/reference/options.md
- package.nix
- src/modules/top-level.nix
- src/modules/update-check.nix
- Fixes an issue where the shell would have to be reloaded twice to pick up caching dependencies.
- Add a `devenv direnvrc` command to let devenv upgrade the direnv integration.
- Export a version env var to track direnvrc versions.
- Add messages to prompt users to switch to the new direnvrc. Can be disabled.
> direnv: create upgrade path for direnvrc and fix more bugs

- src/modules/languages/go.nix
Added iferr to the list of base packages installed for go language support.
> go: added iferr to go language module to support vim-go

- src/modules/services/mysql.nix
> Fix regression when Mysql user password is not set

- docs/reference/options.md
- src/modules/outputs.nix
- src/modules/scripts.nix
- src/modules/tasks.nix
- src/modules/top-level.nix
This is a bit more useful and passes the stricter rules I apply in flake-parts docs.
Would you be interested in having such a check here in devenv?
> docs: Use defaultText

- devenv/src/cnix.rs
- docs/reference/options.md
- src/modules/cachix.nix
The previous logic assumed that cache setup should be disabled if `cachix.pull` is empty, but that `devenv` is always a default cache. We now read in `cachix.enable` and use that to enable/disable setting up caches.
> cachix: use `cachix.enable` to disable cache setup logic

- docs/integrations/github-actions.md
When following the advice to always use a devenv shell for `run`, an extra change to not do this for the devenv install step is required.
> docs: update github actions integration

- src/modules/containers.nix
Hi, I was recently trying to use the **container sub command** and noticed it would fail to build with something like the following output every time it would run:
```
INFO[0000] Image has been written to /nix/store/5ciiy94r2g6x4vp3ci9g3j62pf9v7yds-image-shell.json
/nix/store/5ciiy94r2g6x4vp3ci9g3j62pf9v7yds-image-shell.json
✔ Building shell container in 22.0s.
• Copying shell container ...• Running /nix/store/knb9p6bnp6a9csa3w3c9h1ykm4lkyk4c-copy-container /nix/store/5ciiy94r2g6x4vp3ci9g3j62pf9v7yds-image-shell.json docker-daemon:
Copying container /nix/store/5ciiy94r2g6x4vp3ci9g3j62pf9v7yds-image-shell.json to docker-daemon:shell:latest
Container "IMAGE-NAME" uses a "transport":"details" format.
Supported transports:
containers-storage, dir, docker, docker-archive, docker-daemon, nix, …
```
> fix: changed copy script so that 'skopeo' copy functions on nixos

- examples/nur/devenv.nix
- examples/nur/devenv.yaml
Module support was recently dropped.
AFAIK the only way to use NUR now is through an overlay.
> examples: fix nur example

- devenv-run-tests/src/main.rs
- devenv/src/cli.rs
- examples/compose/projectB/devenv.yaml
- tests/rust/devenv.nix
- tests/tasks/devenv.nix
- Clear the environment before running tests. This prevents test failures (or successes) due to environment pollution.
- Copy the test directory's contents to a temporary directory. Avoids polluting the source directory with test files.
- Initialise a git repo in the temporary directory. Allows Nix and git-hooks to correctly find the project root directory.
> devenv-run-tests: improve reproducibility of test runs

- src/modules/integrations/git-hooks.nix
- tests/git-hooks-no-python-leak/devenv.nix
Upstream issue: https://github.com/NixOS/nixpkgs/issues/302376
Python derivations built with `buildPythonApplication` or converted from a library with `toPythonApplication` do not make the distinction between build- and run-time dependencies. When these packages are added to `packages`, their `propagatedBuildInputs` are leaked into the environment. This includes the Python interpreter and other dependencies, which may conflict with the user's configured environment.
This PR symlinks the pre-commit binary to avoid bringing along all of the Python baggage with it.
Fixes https://github.com/cachix/devenv/issues/1644.
> git-hooks: prevent pre-commit from leaking build inputs into env

- docs/overrides/home.html
- src/modules/services/prometheus.nix
- tests/prometheus/.test.sh
- tests/prometheus/devenv.nix
feat(services): add prometheus service
Adds a new service module for running Prometheus in devenv environments.
Includes configuration options for scraping, storage, and experimental
features. Tested with basic HTTP endpoint verification.
closes https://github.com/cachix/devenv/issues/470
> feat(services): add prometheus service

- src/modules/tests.nix
This happened (posted to discord yesterday):
```
I'm now since a few months using devenv again, and get a strange error for `wait_for_port 34000` => `bash: line 1: /dev/tcp/localhost/34000: Connection refused`??? (Executed within `enterTest`) This confuses me, when I contributed to `devenv`'s `postgres` service a few months ago `wait_for_port` trivially worked?
```
This seems to be a bug (see e.g. https://unix.stackexchange.com/questions/777846/stdin-redirection-from-dev-tcp-localhost-port for a bit more insight), or at least the method used for port checking is not robust and not portable; this PR aims to fix this.
> fix/robustify wait_for_port function

- devenv-eval-cache/src/command.rs
Fixes #1715.
Related to https://github.com/cachix/devenv/issues/1525.
Makes sure we don't mix tokio threads with non-tokio processes.
> eval-cache: prevent deadlock reading pipes on 1-cpu machines

- src/modules/languages/python.nix
Fixes #1712 
I decided to make the two tasks exclusive when sync is enabled. Hope that is OK.
Sadly I could not figure out how to reproduce the failure in the test. The current test _should_ have already failed.
Is it correct that the interpreter is not being set in the `uv sync` command?
> python: fix uv sync venv activation

- src/modules/process-managers/process-compose.nix
Improves the UX by letting users inspect the logs.
> process-compose: keep the TUI open after all processes fail

- docs/reference/options.md
- src/modules/tasks.nix
`tasks.<name>.binary` is now an optional override, in case `lib.getExe` (i.e. `meta.mainProgram`) returns something that doesn't work.
This fixes an upcoming issue in nixpkgs/master where the pname for `bash` is changing to `bash-interactive` by default. Using the `pname` as the name of the binary will break tasks.
> tasks: use `lib.getExe` to fetch the package binary by default

- docs/containers.md
- With the missing empty line between the text paragraph and the bullet point list, the list was not rendered as one.
- I added the comprehensive tutorial on how to set up linux builds on macos: these might be easier and faster to follow for people than the reference-like official documentation.
> Fix list formatting, add nixcademy tutorial

- src/modules/process-managers/mprocs.nix
mprocs is a simple TUI-based process manager written in rust
it is somewhat similar to process-compose but works far better out of the box on clean shells  (view https://github.com/cachix/devenv/issues/1492#issuecomment-2652022265)
> Added support for mprocs process manager

- src/modules/languages/javascript.nix
If the installed version of yarn is newer than v2 (currently v4.6), the —cwd option needs to be specified as the first argument. This modification is backward compatible.
Example error:
Usage Error: The --cwd option is ambiguous when used anywhere else than the very first parameter provided in the command line, before even the command path
$ yarn install [--json] [--immutable] [--immutable-cache] [--refresh-lockfile] [--check-cache] [--check-resolutions] [--inline-builds] [--mode #0] Install failed. Run 'yarn install' manually.
> Move cwd for yarn to start of args to support newer versions

- src/modules/scripts.nix
Similar to #1745 but for scripts now.
> scripts: use lib.getExe to fetch the package binary by default

- docs/tasks.md
The example previously wrote what appears to be Nix code to the output file instead of JSON like it expects.
> docs: fix invalid JSON in DEVENV_TASK_OUTPUT_FILE example

- src/modules/services/postgres.nix
I had some trouble creating a database and user which contains a dash "-" in its name.
The name was "unit-tests" both, which causes some syntax errors during the creation of the database and during the grant process.
These changes fixes it for me.
```nix
initialDatabases = [{
name = "unit-tests";
schema = ./tests/fixtures/db.sql;
user = "unit-tests";
pass = "unit-tests";
}];
```
> fix(postgres-service): add quotes to resource names

- RELEASE.md
- devenv/Cargo.toml
- devenv/src/flake.tmpl.nix
- docs/.pages
- docs/overlays.md
- docs/reference/options.md
- examples/overlays/devenv.nix
- package.nix
- src/modules/top-level.nix
Fixes #478
Fixes #637
```nix
{
overlays = [
(final: prev: {
nodejs = prev.nodejs-18_x;
})
];
}
```
[docs](https://local-overlays.devenv.pages.dev/overlays/)
> Support local overlays

- devenv/src/cnix.rs
- devenv/src/devenv.rs
- devenv/src/main.rs
Fixes #1769.
Removes an extraneous call to create `.devenv/gc` when creating the devenv lib and modifies to cnix to optionally initialise the database later.
In theory, init should only be in the CLI binary. It doesn't even need the library to work.
We should merge https://github.com/cachix/devenv/pull/1721 first to resolve conflicts.
> devenv: don't create local project directories on `devenv init`

- docs/reference/options.md
- src/modules/top-level.nix
- tests/macos-custom-apple-sdk/devenv.nix
- tests/macos-no-default-sdk/devenv.nix
- Remove the default SDK from stdenv. This is currently not easy to do.
- Ensure users can set their own SDK if necessary via `packages`.
Fixes #1674.
Fixes #1641.
> macos: add an option to configure the macOS SDK or remove it completely

- src/modules/integrations/dotenv.nix
The `dotenv` module prints informative messages on the `stdout`, which causes a problem on the CI because, in some cases, the output of a command is required for another step. 
```sh
data=$(devenv shell -- <command>)
echo "------------------------"
echo "$data"
echo "------------------------"
echo "data=$data" >> "$GITHUB_OUTPUT" 
```
When GH actions parse the output from the previous code snippet, the following error occurs:
```
------------------------
💡 The dotenv file '.env' was not found.
To create this file, you can copy the example file:
$ cp .env.example .env
<command output>
------------------------
Error: Unable to process file command 'output' successfully.
Error: Invalid format '   To create this file, you can copy the example file:'
```
Other modules like `update-check` …
> dotenv: Redirect informative messages to `stderr`

- devenv/src/flake.tmpl.nix
- src/modules/top-level.nix
Since overlays require CLI-level changes to module eval, all of the changes should be shipped with the CLI. Othewise, newer CLI versions will not work with older modules.
Continuation of #1768.
> devenv: make overlay changes backwards compatible with older modules

- devenv-run-tests/src/main.rs
- devenv/src/cnix.rs
- devenv/src/devenv.rs
- devenv/src/main.rs
Removes `nix develop` that was used for the underlying shell and replaces it with a custom shell launcher.
We still rely on Nix to generate the rcfile script for us, but this is a good first step towards a snix shell.
As a bonus, by reducing the number of calls to the Nix CLI and making better use of our caching system, this drastically improves the time-to-shell.
For the devenv repo, the numbers are:
- Linux: 500ms -> 150ms
- macOS: 1300ms -> 300ms
> devenv: replace `nix develop` with a custom shell launcher

- docs/reference/options.md
- docs/supported-languages/typst.md
- src/modules/languages/typst.nix
In order to make some fonts available to Typst, the latter supports the `TYPST_FONT_PATHS` environment variable. Sure, fonts can be made available by simply adding them to the `packages`. However, doing so results in Typst seeing them as system fonts, so you can't really know if it mistakenly chooses a font that is installed on your computer instead. Setting them via `TYPST_FONT_PATHS`, in combination with running Typst with the `--ignore-system-fonts` flag, allows for a fully reproducible build.
> Add Typst fontPaths option

- docs/reference/options.md
- docs/supported-languages/typst.md
- src/modules/languages/typst.nix
This is a follow-up to #1791. I hadn't noticed but there is an extra bracket and a misplaced space in the example
```
[ "${pkgs.roboto}/share/fonts/truetype "] ]
```
This changes it to
```
[ "${pkgs.roboto}/share/fonts/truetype" ]
```
> Fix Typst fontPaths example

- devenv/src/cli.rs
- devenv/src/devenv.rs
- devenv/src/main.rs
hi, thanks for devenv!
This change allows to specify multiple processes when running `devenv up`/`devenv processes up`
> allow to run multiple process at once

- containers/devcontainer/Dockerfile
Fixes #1795.
I think I removed this fix when doing devcontainer fixes because its purpose wasn't documented.
> devcontainer: fix suspicious permission error

- devenv-run-tests/src/main.rs
- devenv/src/config.rs
- devenv/src/main.rs
`--override-input` would previously completely overwrite the existing input. This could end up removing any existing follows and flake options.
Fixes #1801.
> devenv: preserve existing options when overriding inputs

- devenv-eval-cache/src/command.rs
- devenv/src/cnix.rs
Overrides go through flake.json, instead of the nix commands. This made them invisible to the caching system.
> eval-cache: bust the cache when using input overrides

- docs/common-patterns.md
- docs/packages.md
- Add reference on packages docs for common patterns (I lost half an hours to find it).
- Fix auto-numbering on common-patterns markdown.
> docs: package reference common patterns

- flake-module.nix
- flake.nix
- templates/flake-parts/.envrc
- templates/flake-parts/flake.nix
- Avoid creating a temporary file in each direnv evaluation.
- Provide a `flakeModules.readDevenvRoot` output for simpler handling of pure devenv.root in flakes.
- Use that module by default.
Smoother workaround for https://github.com/cachix/devenv/issues/1764
@moduon MT-1075
> fix: better pure devenv-root handling in flakes

- devenv-eval-cache/src/command.rs
- devenv-eval-cache/src/db.rs
Prevent cache invalidation stemming from multiple file paths that differ in the timestamps only because of the truncation at the database layer.
Fixes #1823.
The previous iteration of this PR switched the database layer to microsecond precision. This has been removed because our database setup logic did not fully drop the database if it encountered migration errors. To retain backwards-compatibility, that should be done in a separate version.
> eval_cache: prevent cache invalidation due to timestamp precision issues

- devenv-eval-cache/src/command.rs
- devenv/src/cnix.rs
- devenv/src/config.rs
- devenv/src/devenv.rs
- flake-module.nix
- Sort the flake inputs (flake.json) deterministically to prevent random cache misses.
- Switch to BTreeMap for all sorts of inputs where we'd prefer to have a deterministic order.
- Re-hash the input hash to prevent it from growing O(n) with inputs.
> devenv: deterministically sort flake inputs to aid caching layer

- docs/reference/options.md
- docs/supported-services/postgres.md
- src/modules/services/postgres.nix
- Use one of the IP addresses from `listen_addresses` if configured.
- Handles special listen addresses, like `*`, `0.0.0.0`, and `::`.
- Only set `PGPORT` if using IP addresses.
- Expand the docs for `listen_addresses` using the official postgres docs as reference.
> postgres: improve how PGHOST is computed

- src/modules/languages/python.nix
Forces uv not to download binaries in case of mismatch
Implements #1820
I also considered adding an assert for checking if the version of the python is in the set specified by `project.requires-python` but I'm not sure if that makes sense in devenv context.
> Force uv not to download

- Cargo.lock
- Cargo.toml
- devenv-eval-cache/src/command.rs
- devenv/Cargo.toml
- devenv/src/devenv.rs
- devenv/src/lib.rs
- devenv/src/util.rs
When watching generated files, we need to take care not to touch the files unless they change. direnv only compares the modification time, not the file contents, so it's triggered every time we write these files. Even worse, the vscode extension is happy to re-evaluate the shell without waiting for the previous one to finish loading.
Fixes #1824.
> direnv: fix excessive reloads

- CLAUDE.md
- devenv-tasks/src/lib.rs
- devenv/src/cli.rs
- devenv/src/cnix.rs
- devenv/src/devenv.rs
- devenv/src/flake.tmpl.nix
- docs/basics.md
- tests/cli-options/.test.sh
- tests/cli-options/devenv.nix
- tests/cli-options/devenv.yaml
It's common to be able to build matrix on CI jobs, so let's allow passing options via CLI:
```
devenv --option services.redis.enable:bool true test
```
cc @staticdev
> Add --option CLI flag for overriding configuration options

- docs/blog/posts/devenv-v1.6-ad-hoc-developer-environments.md
- docs/guides/.pages
- docs/guides/profiles.md
Sometimes it's useful to be able to only run a subset of developer environment and choose.
[guide preview](https://docs-profiles.devenv.pages.dev/guides/profiles/)
Fixes #1426
> docs: document how to use profiles

- devenv/src/devenv.rs
- devenv/src/lib.rs
- devenv/src/main.rs
- src/modules/tests.nix
Evaluates the dev env once and applies it to both the spawned processes and the tests. This reduces the number of shell evaluations we need to do and prevents task conflicts.
> devenv: fix race conditions setting up the shell during tests

- devenv.nix
Tests for the issue described in https://github.com/cachix/devenv/issues/1769
Fixed by https://github.com/cachix/devenv/pull/1771
I had to remove the first test, because an interactive confirmation was added. The tests still worked in CI, because the command fails to allocate an interactive terminal.
> tests: add cli test for init with target path

- flake.nix
- src/modules/tasks.nix
Expose `devenv-tasks` in the flake.
> tasks: export devenv-tasks in the flake

- examples/python-django/devenv.nix
- examples/rubyonrails/.test.sh
- src/modules/services/postgres.nix
- src/modules/tests.nix
If using process-compose, `wait_for_processes` allows waiting for all processes that implement readiness_probe.
> tests: add `wait_for_processes`

- src/modules/integrations/git-hooks.nix
- tests/git-hooks-all-disabled/.setup.sh
- tests/git-hooks-all-disabled/devenv.nix
To keep .pre-commit-config.yaml in sync when all hooks are disabled
#1748
> Uninstall git-hooks when disabled

- src/modules/languages/dotnet.nix
Newer nixpkgs wrap the actual dotnet package, and therefore DOTNET_ROOT should point to the unwrapped package.
Also, pointing DOTNET_ROOT to the actual dotnet location (in /share/dotnet) fixes some packages that may have problems finding dotnet using the binary (like omnisharp)
Will most likely fix https://github.com/cachix/devenv/issues/1722
> Fix DOTNET_ROOT

- devenv/src/flake.tmpl.nix
- docs/reference/options.md
- src/modules/outputs.nix
- src/modules/tasks.nix
Improve how we inspect options and their types by using the module helper functions.
This fixes #1902, where `services.keycloak.database` was being incorrectly classified as an option because it has a nested option named `type`.
> outputs: fixes `devenv build` when building all outputs

- devenv/src/config.rs
- devenv/src/flake.tmpl.nix
- docs/devenv.schema.json
- docs/reference/options.md
- docs/reference/yaml-options.md
- tests/nixpkgs-config/devenv.nix
- tests/nixpkgs-config/devenv.yaml
This PR aims to allow setting some of the attribute of the `config` attribute set that is normally passed as argument when importing Nixpkgs.
An example that is currently not supported (but would be after this PR):
```nix
{
pkgs = import nixpkgs {
inherit system;
overlays = [ ... ];
config = {
allowUnfree = true;
allowBroken = true;
cudaSupport = true;
cudaCapabilities = [
"7.5"
"8.6"
"8.9"
];
};
};
}
```
We have a project where we work with CUDA and override various packages (e.g. OpenCV) to have CUDA support enabled. Currently, we are using `devenv` with the flake integration, but would like to now migrate to using the `devenv` command and `devenv.yaml`/`devenv.nix` to benefit from faster load times.
We also have the added complexity of supporting 2 architectures: x86 and aarch64 with …
> Allow configuration of the Nixpkgs instance on a per-system basis

- docs/containers.md
Linking out to follow container options similarly to link from git hooks option. These are not explicitly called out and these options were only found by digging through the containers.nix module.
> Update containers documentation with link to all options

- src/modules/services/keycloak.nix
- tests/keycloak/.test.sh
- This adds better Git diffability for the realm-export in the `keycloak` service.
- Also fixes a bug for the health check url which was wronlgy using `cfg.hostname` instead of `localhost:9000`.
Fixed: #1912
> fix(keycloak): add realm export Git diff clean and health check url fix

- src/modules/languages/go.nix
Handle derivations that take a `buildGoLatestModule`.
> go: fix the go version override for gpls

- src/modules/outputs.nix
lib.literalExample is deprecated, use lib.literalExpression instead
see https://github.com/NixOS/nixpkgs/blob/26be80f33b8dd36165f6f929755fad9be068a312/lib/options.nix#L690
> remove usage of debrecated literalExample

- docs/reference/options.md
- docs/supported-services/opensearch.md
- src/modules/services/opensearch.nix
- Links the core plugins that ship with opensearch.
- Disable the security module, which otherwise fails OOTB if SSL is not configured.
For plugins, it would be nice to have a plugins option that uses `buildEnv`. These should be packaged in nixpkgs: https://github.com/opensearch-project/OpenSearch/tree/main/plugins, much like `elasticsearchPlugins`.
Fixes https://github.com/cachix/devenv/issues/1870.
> opensearch: link core plugins and disable security by default

- devenv/src/devenv.rs
hi, there's a regression in 1.6 that joins the `devenv up` args without a space so it doesn't work properly with multiple args
> fix up args to join with space

- docs/reference/options.md
- docs/supported-services/keycloak.md
- src/modules/services/keycloak.nix
- Enable and disable realm export with
```nix
scripts.exportRealm = false;
processes.exportRealms = false;
```
- Only make the process `keycloak-realm-export-all` show up if at least some `realm.XXX.export = true` are set.
> feat: add enable/disable toggles for realm export

- devenv-eval-cache/Cargo.toml
- devenv-eval-cache/src/command.rs
- devenv-eval-cache/src/lib.rs
Live integration tests with Nix for the eval-cache feature. This will make it easier to catch issues when bumping Nix.
> eval-cache: add integration tests

- devenv-cache-core/src/file.rs
- devenv-tasks/src/task_cache.rs
- devenv-tasks/src/tests/mod.rs
- devenv/src/mcp.rs
- package.nix
Continuation of #1955.
The `set_current_dir` approach is not safe when the tests are run in parallel. We explicitly provide the temp root dir to the MCP server in this case.
Removed the thread sleeps in task tests in favour of modifying the mtime to speed things up. macOS has a resolution limit of 1 second, so this should let us spend less time waiting around in tests.
> mcp: fix race condition in tests

- src/modules/languages/python.nix
In this module case:
```
{
languages.python = {
enable = true;
package = pkgsPinned.python;
uv.enable = true;
};
}
```
when I run `uv venv ...` it will take up my python version from a virtual environment (activated on shell entry by `.zshrc` etc , of course this I should avoid). But here is a simple fix which IMO was missed. 
- `uv` must always use the correct python version by forcing it to use it with `UV_PYTHON`.
- No fix for poetry so far, as poetry does not nicely play with this and is also deprecated in terms of modernity.
> fix: add `UV_PYTHON` to force uv to use the correct python

- docs/reference/options.md
- docs/supported-languages/rust.md
- examples/rust-wasm-cross/devenv.yaml
- examples/rust/devenv.yaml
- src/modules/languages/rust.nix
Adds basic support for specifying the version of the rust toolchain you want to use.
This change moves away from using fenix, to instead using rust-overlay.
It seems to work just fine, and is somewhat minimal invasive.
TODO:
Example:
```nix
{
languages.rust = {
enable = true;
};
}
```
```yaml
inputs:
devenv:
url: github:eyJhb/devenv/rust-versions
```
> rust: replace fenix with rust-overlay allow specifying rust version

- docs/reference/options.md
- docs/supported-languages/python.md
- src/modules/languages/python.nix
- tests/python-uv-sync-all-groups/devenv.nix
- tests/python-uv-sync-all-groups/pyproject.toml
This PR adds support for the `--all-groups` flag in devenv's Python module, allowing users to install all dependency groups defined in their `pyproject.toml` file with a single flag.
Currently, devenv supports the `--all-extras` flag to install all optional dependencies, but there's no equivalent functionality for dependency groups. Users who want to install all groups must specify each one individually, which can be cumbersome when working with projects that have multiple dependency groups.
- Added a new `allGroups` option to the Python module configuration
- When `allGroups` is enabled, the `--all-groups` flag is passed to the underlying package manager commands
- The implementation follows the same pattern as the existing `--all-extras` functionality
Docs: …
> feat: add all-groups for Python dependency

- devenv-tasks/src/task_cache.rs
Adds a flush to the following test to hopefully fix the intermittent build failure on macOS. Also, a small lint to remove an extra String allocation.
```
> failures:
>
> ---- task_cache::tests::test_file_modification_detection stdout ----
>
> thread 'task_cache::tests::test_file_modification_detection' panicked at devenv-tasks/src/task_cache.rs:317:9:
> assertion failed: !cache.check_modified_files(task_name, &[path_str.clone()]).await.unwrap()
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
>
>
> failures:
>     task_cache::tests::test_file_modification_detection
>
> test result: FAILED(B. 25 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 7.91s
>
> error: test failed, to rerun pass `-p devenv-tasks --lib`
```
> task_cache: attempt to fix intermittent test failure

- Cargo.lock
- devenv-run-tests/src/main.rs
- devenv-tasks/src/task_cache.rs
- devenv-tasks/src/tests/mod.rs
- devenv/Cargo.toml
- devenv/src/config.rs
- devenv/src/devenv.rs
- devenv/src/main.rs
- devenv/src/mcp.rs
- devenv/src/nix.rs
- devenv/src/nix_backend.rs
- devenv/src/snix_backend.rs
We have a few places in the codebase that are, as they say, embarrassingly parallel. But any effort to improve on that is hindered by the use of `mut self`, both in the devenv struct and in the Nix backend.
This PR removes those limitations allowing both devenv and nix commands to be called concurrently.
> devenv: async-ify the core state

- docs/reference/options.md
- docs/supported-languages/rust.md
- src/modules/languages/rust.nix
This feature should be opt-in because we can't guarantee it will work by default.
Examples:
- #1951 If RUSTFLAGS is set, cargo will skip reading .cargo/config.toml.
- #1684 Building for an architecture which doesn't have an explicit target and uses a custom toolchain linker.
> rust: make the mold linker opt-in

- devenv/src/devenv.rs
- devenv/src/mcp.rs
- devenv/src/nix.rs
- devenv/src/nix_backend.rs
- devenv/src/snix_backend.rs
The `add_gc` approach we use doesn't protect us from Nix garbage-collecting the store path between running `nix build` and calling `add_gc`. This approach uses `out-link` instead to hopefully reduce the risk of losing store paths to auto-gc.
This is particularly important for our CI. The machine to watch is the aarch64-darwin runner, which has a disk much too small for what we're asking it to do 🙃
> devenv: protect internal Nix builds from untimely GC

- src/modules/languages/python.nix
**Underlying Issue**
Since #1959, UV_PYTHON is forced to devenv's python interpreter. However, it is the unwrapped interpreter. This of course breaks the native libs functionality.
**To reproduce**
Create a devenv.nix with `languages.python.uv.sync.enable = true`:
```nix
{ pkgs, config, inputs, ... }:
{
languages.python = {
enable = true;
venv.enable = true;
uv = {
enable = true;
sync.enable = true;
};
};
}
```
Check UV_PYTHON variable from shell:
```sh
echo $UV_PYTHON
> /nix/store/fqm9bqqlmaqqr02qbalm1bazp810qfiw-python3-3.12.9/bin/python3.12 <- This is an unwrapped interpreter
```
**Fix**
Just use the wrapped python bound to `package` in `python.nix`
> fix: correctly set UV_PYTHON to the wrapped python interpreter

- src/modules/languages/rust.nix
In the switch from fenix to rust-overlay in #1500, the final toolchain was not correctly patched. This resulted in runtime linker errors, where tools like clippy were linked against the wrong librustc.
PR #1983 was an attempt at adjusting our APIs to better suit the toolchain/profile design of rust-overlay. 
This PR retains the API compatibility at the cost of using private APIs.
> rust: fix toolchain creation with rust-overlay

- docs/reference/options.md
- docs/supported-languages/rust.md
- src/modules/languages/rust.nix
Unlike fenix, rust-overlay does it's patching when building the
toolchain profile from a set of resolved components. For that reason we
can't use the unpatched toolchain components directly to fixup the git
hooks packages.
> rust: expose `toolchainPackage` and use it correctly override git hooks

- devenv-tasks/src/tasks.rs
- devenv-tasks/src/tests/mod.rs
For example, for 3 level tasks, you can now run the second level:
```
devenv tasks run ci:lint
```
Fixes #2017.
> tasks: allow running multi-level sub-tasks

- flake.lock
Testing https://github.com/cachix/nix/pull/8
> nix: fix a regression where `path` inputs were locked

- src/modules/languages/c.nix
- src/modules/languages/cplusplus.nix
Adding clang after clang-tools in dependency chain can cause issue with clangd of kind (compile_commands.json
Fixes issue from #1387 by adding clangd(clang-tools) as a dependency into languages.cplusplus / languages.c
This issue was also mentioned in Nixpkgs: https://github.com/NixOS/nixpkgs/issues/76486
Important note: clang-tools must be added before clang (there's some issue in initialization if otherwise)
> Fix clangd error: compile_commands.json not found when enabling languages.c and languages.cplusplus

- devenv/src/main.rs
Since the stdout printing was moved out of the library function, the
legacy flag test failed.
The legacy support has been refactored into a single block that maps the
flags to a valid container subcommand, if missing.
This deduplicates the calls to the library commands, preventing mistakes
like the one that caused the test to fail, and makes it easy to remove
the legacy support.
> devenv: fix legacy container flags test

- src/modules/services/mysql.nix
We're currently running some services on docker while we're porting things to nix. In these cases it's necessary to customize the host parameter of the mysql users being created, as localhost is specific to each container's network namespace.
> mysql: add ensureUsers.*.host option

- devenv/src/devenv.rs
- devenv/src/nix.rs
- docs/reference/options.md
This effectively watches all of the template arguments passed to the flake for changes.
We previously removed this because it caused issues with direnv's file watching. With safeguards now in place to avoid touching unchanged files, this should be safe to re-introduce.
Fixes #2048.
> eval-cache: bust eval-cache when inputs to .devenv.flake.nix change

- docs/getting-started.md
home-manager doesn't have an option named `environment.systemPackages`.
> docs: fix installing in home-manager

- devenv/src/flake.tmpl.nix
- src/modules/flake.nix
We can query the options attrset directly instead of using custom outputs.
In case anyone is depending on these (for whatever reason), there will be a brief deprecation period.
> devenv: deprecate feature detection output flags

- src/modules/languages/rust.nix
This flag should no longer be necessary + the path was incorrect.
Fixes #2071.
> rust: drop `-iframework` flag on darwin

- src/modules/languages/python.nix
Setting `UV_PYTHON_PREFERENCE=system-only` make `uv` only using the python interpreter it finds on the `PATH` which si what we want. 
Maybe in the future that can be relaxed, but I think this is a special knob to escape into the system which is not the purpose of determinism.
Fixes: #1959
> fix(python): make `uv` discover the correct python

- devenv/src/config.rs
- devenv/src/flake.tmpl.nix
- docs/devenv.schema.json
- docs/reference/yaml-options.md
- tests/permitted-unfree/devenv.nix
- tests/permitted-unfree/devenv.yaml
Fixes #2081.
This doesn't exist yet in nixpkgs and is built on top of `allowUnfreePredicate`.
> devenv: implement `permittedUnfreePackages`

- devenv.lock
- flake.lock
Remove the dirty repo fingerprinting code.
Since we allow untracked files, this causes severe performance issues in certain repos.
Fixes #2042.
Nix uses a different file system accessor in impure mode. With lazy trees enabled, we couldn't fetch the original store path through this accessor. We now implement a caching layer to keep track of the original path.
Fixes #2059.
> nix: fix several regressions

- devenv/direnvrc
- devenv/init/.envrc
- devenv/src/main.rs
- tests/direnv/.test.sh
This lets tasks configure logging when used via direnv.
Fixes #2098.
> direnv: pass `DEVENV_CMDLINE` to the shell

- src/modules/languages/ruby.nix
The common naming convention is `.ruby-version` among rbenv(1), asdf(1),
etc.
> Fix rubyVersionFile example

- docs/editor-support/intellij.md
This adds a workaround to use PyCharm and other IDEs that expect python to be installed either on the OS level, or via a local virtual environment folder `.venv` or `venv`.
After adding the shell script, the IDE will pickup the python interpreter automatically.
> docs: added pycharm and python integration documentation

- devenv-tasks/src/task_state.rs
Fixes #2109.
Adds a `.json` extension for tools that aggressively check for this.
Also adds a prefix for debugging purposes.
> tasks: add json extension and a prefix to the task output file

- docs/blog/posts/closing-the-nix-gap-from-tools-to-packaged-applications.md
- docs/reference/options.md
- docs/supported-languages/rust.md
- examples/rust/.test.sh
- examples/rust/devenv.nix
- examples/rust/devenv.yaml
- src/modules/languages/rust.nix
Allow packaging Rust projects using [cargo2nix](https://github.com/cargo2nix/cargo2nix).
```nix
{ pkgs, lib, config, ... }:
let
mypackage = config.languages.rust.import ./. {};
in {
languages.rust.enable = true;
packages = [ mypackage ];
outputs = {
inherit mypackage;
};
}
```
> Rust: import functionality

- docs/editor-support/intellij.md
I requested at Jetbrains to mark the plugin as deprecated. I don't use Nix / Devenv anymore and won't want to invest further my free time
> Remove PHP IDE integration section from documentation

- examples/scripts/devenv.nix
- src/modules/scripts.nix
The `packages` were being made available to the build script for the script, not the script itself.
I've also added a test for this in `examples/scripts`.
Additionally:
The `runCommand` script looked suspiciously similar to `writeShellScript`.
To pass PATH correctly, I had to use a wrapper script. Another option would be `env`, but that messes with exit codes, signals, and what not. Open to alternatives.
The scripts in `examples/scripts` are now tested in CI. I replaced the curl example to test accessing top-level `packages` without making external requests.
> scripts: fix the `packages` option

- docs/blog/posts/devenv-v1.7-cuda-support-enhanced-tasks-mcp-support.md
> fix yaml syntax

- docs/reference/options.md
- docs/supported-services/opentelemetry-collector.md
- src/modules/process-managers/process-compose.nix
- src/modules/processes.nix
- src/modules/services/opentelemetry-collector.nix
`type.attrs` does not merge options, making it impossible to override.
Partial fix for #2156.
> process-compose: fix overriding per-process options

- examples/starship/devenv.nix
- src/modules/integrations/starship.nix
Main use case for this is being able to merge in configuration from imports and profiles
> starship: add inline configuration option

- src/modules/process-managers/process-compose.nix
We've had a lot of complaints about `process-compose` trying to attach to non-existent instances in recent months.
I think the issue is this commit: https://github.com/cachix/devenv/commit/053c79211a274098b5a48ccf2ff47873316e048b
`process-compose` will skip cleaning up the socket file if it exits abnormally.
While `process-compose up` is capable of restarting in this situation, `process-compose attach` is not and will continue trying to reconnect. Our simple file check is not a robust enough check.
This PR uses `socat` to test for all 3 conditions: the file exists, the file is a socket, the socket has a bound listener.
We've also had feedback that it wasn't intuitive that `devenv up` would try to reconnect to another `process-compose` instance.
This is believable because the "Attaching to …
> process-compose: check the socket for liveness before attaching

- docs/common-patterns.md
This feels more complicated than it should be. Especially setting the `export DYLD_FALLBACK_LIBRARY_PATH="${rosettaPkgs.lib.makeLibraryPath [ rosettaPkgs.gcc14.cc] }:$DYLD_FALLBACK_LIBRARY_PATH"` feels like it should just go into either `languages.python.libraries` or into `packages`. I didn't get that to work however.
This would fix #1603
> Add documentation on how to enable compilation of binary dependencies.

- docs/blog/posts/devenv-v1.6-extensible-ad-hoc-nix-environments.md
This PR updates a link in the blog post [devenv 1.6: Extensible Ad-Hoc Nix Environments](https://devenv.sh/blog/2025/04/25/devenv-16-extensible-ad-hoc-nix-environments/).
> docs: Update link to Profiles guide in blog post

- docs/packages.md
This PR updates the documentation to use the correct repository for the `nix-index-database` in the example shell session.
> docs: Fix GitHub path for nix-index-database in shell session

- devenv-tasks/Cargo.toml
- devenv-tasks/src/config.rs
- devenv-tasks/src/lib.rs
- devenv-tasks/src/main.rs
- devenv-tasks/src/privileges.rs
- devenv-tasks/src/task_state.rs
- devenv-tasks/src/tasks.rs
- devenv/src/devenv.rs
- src/modules/process-managers/process-compose.nix
- src/modules/processes.nix
- src/modules/tasks.nix
If a user enables `process-compose.is_elevated`, our task runner should be able to handle being run under `sudo`.
This involves:
- configuring process-compose to pass-through a few required variables
- dropping privileges during setup (i.e. writing to filesystem) and `sudo`-ing the task process directly
Also:
- devenv-tasks will now show a much better error is no task config is found, instead of `NotPresent`.
- devenv-tasks now accepts a `task-file` directly and via an env var
Our task/process runner should handle this directly in the future, i.e. have options to run certain processes in an elevated shell. What we don't currently have is a UI flow to request the auth, which is handled by process-compose.
Fixes #2157.
> tasks: support running in an elevated shell

- docs/extending.md
Removed extra . causing the following syntax error: `unexpected '.', expecting ID or OR_KW or DOLLAR_CURLY or '"'`
> docs: fix syntax error in /extending/#module-replacement code block.

- devenv/src/flake.tmpl.nix
- tests/cli-module-regression/README.md
- tests/cli-module-regression/devenv.nix
- tests/cli-module-regression/devenv.yaml
Fixes the feature check for the new git option, making the new CLI compatible with older module revisions.
Added a very basic test to try to catch regressions like this.
Fixes #2193.
> devenv: fix missing `git` option regression

- src/modules/integrations/git-hooks.nix
I replaced the name of the binary 'cause I don't feel comfortable naming `prek` as `pre-commit` let me know if you don't like it.
> Make it posible to override pre-commit binary
